<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'
import { Calendar, Download, Expand, FileImage, FileText, FolderOpen, Goal, Printer, RefreshCcw, Save, Trash2, X } from 'lucide-vue-next'
import Button from '@/components/ui/Button.vue'
import Card from '@/components/ui/Card.vue'
import Input from '@/components/ui/Input.vue'
import Label from '@/components/ui/Label.vue'
import { getLocaleFromUrl, syncLocaleInUrl } from '@/lib/i18n'
import { formatDateLong, formatGoalTime, formatPaceValue, isValidISODate } from '@/lib/planner'
import { usePlannerStore } from '@/stores/planner'
import type { AppLocale, PlannerForm, RaceType, SavedPlanEntry, TrainingPlan, TrainingSession } from '@/types/planner'

const planner = usePlannerStore()
const exportElement = ref<HTMLElement | null>(null)
const localError = ref('')
const isExporting = ref(false)
const isPreviewModalOpen = ref(false)
const savePlanName = ref('')
const currentLocale = ref<AppLocale>(getLocaleFromUrl())
const importFileInput = ref<HTMLInputElement | null>(null)
const hasManualEdits = ref(false)
const dayEditorElement = ref<HTMLElement | null>(null)
const canInstallPwa = ref(false)
const isAppInstalled = ref(false)
const deferredInstallPrompt = ref<BeforeInstallPromptEvent | null>(null)

interface BeforeInstallPromptEvent extends Event {
  prompt: () => Promise<void>
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed'; platform: string }>
}

const messages = {
  nl: {
    langName: 'Nederlands',
    appBadge: 'Training Planner',
    appTitle: 'Marathon & Running Planner',
    appSubtitle: 'Vul je doeltijd, wedstrijddatum of aantal trainingsweken in en krijg automatisch een planning.',
    settings: 'Instellingen',
    language: 'Taal',
    installApp: 'Installeer app',
    targetDistance: 'Doelafstand',
    customDistance: 'Eigen afstand (km)',
    customDistancePlaceholder: 'Bijv. 15',
    goalTime: 'Doeltijd (uu:mm of uu:mm:ss)',
    goalTimePlaceholder: '03:45 of 01:48:30',
    planBasedOn: 'Plan op basis van',
    modeDate: 'Datum',
    modeWeeks: 'Weken',
    raceDate: 'Wedstrijddatum',
    trainingWeeks: 'Aantal trainingsweken',
    daysPerWeek: 'Trainingsdagen per week',
    daysSuffix: 'dagen',
    generatePlan: 'Planning genereren',
    startEmptyPlan: 'Start met lege kalender',
    reset: 'Reset',
    savedPlans: 'Opgeslagen planningen',
    savedPlansHint: 'Geef je planning een naam en bewaar hem lokaal om later opnieuw te openen.',
    savePlanPlaceholder: 'Bijv. Rotterdam voorbereiding',
    savePlan: 'Planning opslaan',
    generateBeforeSave: 'Genereer eerst een planning om op te slaan.',
    noSavedPlans: 'Nog geen opgeslagen planningen.',
    exportPlanJson: 'Planning exporteren',
    importPlanJson: 'Planning importeren',
    open: 'Open',
    delete: 'Verwijder',
    planSummary: 'Planoverzicht',
    summaryRace: 'Doelrace',
    summaryPeriod: 'Periode',
    summaryGoalTime: 'Doeltijd',
    summaryGoalPace: 'Doeltempo',
    summaryWeeks: 'Trainingsweken',
    summaryDays: 'Dagen per week',
    downloadPdf: 'Download PDF',
    downloadImage: 'Download afbeelding',
    downloadIcs: 'Download ICS',
    printTable: 'Afdruk tabel',
    printList: 'Afdruk lijst',
    printModeCompact: 'Compact (1 pagina)',
    printModeReadable: 'Leesbaar (groter)',
    showModal: 'Toon in modal',
    exportPreviewDay: 'Exportvoorbeeld per dag',
    exportPreviewHint: 'Dit weekrooster wordt gebruikt voor afbeelding, PDF en print.',
    editorTitle: 'Run aanpassen per dag',
    editorHint: 'Kies week en dag. Je kan een run toevoegen, type/km wijzigen of verwijderen.',
    editorWeek: 'Week',
    editorDay: 'Dag',
    editorType: 'Type run',
    editorDistance: 'Afstand (km)',
    editorDescription: 'Beschrijving',
    editorDescriptionPlaceholder: 'Voeg extra uitleg toe voor deze run...',
    editorNoRun: 'Geen run op deze dag.',
    editorExistingRun: 'Bestaande run:',
    editorCreate: 'Run toevoegen',
    editorUpdate: 'Run bijwerken',
    editorDelete: 'Run verwijderen',
    trainingPlanLabel: 'Trainingsplanning',
    autoGeneratedPlan: 'Automatisch gegenereerd loopschema',
    week: 'Week',
    date: 'Datum',
    total: 'Totaal',
    detailedPlan: 'Detailplanning met uitleg',
    from: 'Van',
    distance: 'Afstand',
    pace: 'Tempo',
    noPlanYet: 'Nog geen planning',
    noPlanHint: 'Vul links je instellingen in en klik op',
    preview: 'Preview',
    closeModal: 'Sluit schema modal',
    restDay: 'Rustdag',
    unknownPlanningError: 'Planningsfout',
    invalidStoredPlanRemoved: 'Opgeslagen planning bevatte ongeldige datums en is verwijderd. Genereer een nieuw schema.',
    saveFailed: 'Opslaan mislukt.',
    loadFailed: 'Laden mislukt.',
    emptyPlanCreated: 'Lege planning aangemaakt. Vul nu zelf je runs in.',
    exportFailed: 'Export mislukt.',
    importFailed: 'Import mislukt.',
    importInvalid: 'Importbestand is ongeldig.',
    generateBeforeExport: 'Genereer eerst een planning.',
    noExportElement: 'Geen planningselement beschikbaar om te exporteren.',
    imageExportFailed: 'Export naar afbeelding mislukt.',
    pdfExportFailed: 'Export naar PDF mislukt.',
    generateBeforePrint: 'Genereer eerst een planning om te kunnen printen.',
    fileNameBase: 'trainingsplan',
    rangeConnector: 't/m',
    defaultPlanPrefix: 'Planning',
    savedAtPrefix: 'Opgeslagen op',
    raceTypeEasy: 'Rustige duurloop',
    raceTypeRecovery: 'Herstelrun',
    raceTypeInterval: 'Interval training',
    raceTypeTempo: 'Tempo run',
    raceTypeTempoMarathon: 'Marathon tempo',
    raceTypeLong: 'Lange duurloop',
    raceTypeRace: 'Wedstrijd',
  },
  en: {
    langName: 'English',
    appBadge: 'Training Planner',
    appTitle: 'Marathon & Running Planner',
    appSubtitle: 'Enter your goal time, race date or number of training weeks and get an automatic plan.',
    settings: 'Settings',
    language: 'Language',
    installApp: 'Install app',
    targetDistance: 'Target distance',
    customDistance: 'Custom distance (km)',
    customDistancePlaceholder: 'E.g. 15',
    goalTime: 'Goal time (hh:mm or hh:mm:ss)',
    goalTimePlaceholder: '03:45 or 01:48:30',
    planBasedOn: 'Plan based on',
    modeDate: 'Date',
    modeWeeks: 'Weeks',
    raceDate: 'Race date',
    trainingWeeks: 'Training weeks',
    daysPerWeek: 'Training days per week',
    daysSuffix: 'days',
    generatePlan: 'Generate plan',
    startEmptyPlan: 'Start with empty calendar',
    reset: 'Reset',
    savedPlans: 'Saved plans',
    savedPlansHint: 'Give your plan a name and save it locally to open again later.',
    savePlanPlaceholder: 'E.g. Rotterdam build-up',
    savePlan: 'Save plan',
    generateBeforeSave: 'Generate a plan before saving.',
    noSavedPlans: 'No saved plans yet.',
    exportPlanJson: 'Export plan',
    importPlanJson: 'Import plan',
    open: 'Open',
    delete: 'Delete',
    planSummary: 'Plan summary',
    summaryRace: 'Target race',
    summaryPeriod: 'Period',
    summaryGoalTime: 'Goal time',
    summaryGoalPace: 'Goal pace',
    summaryWeeks: 'Training weeks',
    summaryDays: 'Days per week',
    downloadPdf: 'Download PDF',
    downloadImage: 'Download image',
    downloadIcs: 'Download ICS',
    printTable: 'Print table',
    printList: 'Print list',
    printModeCompact: 'Compact (1 page)',
    printModeReadable: 'Readable (larger)',
    showModal: 'Show in modal',
    exportPreviewDay: 'Daily export preview',
    exportPreviewHint: 'This weekly grid is used for image, PDF and print output.',
    editorTitle: 'Edit run by day',
    editorHint: 'Choose week and day. You can add a run, change type/km, or remove it.',
    editorWeek: 'Week',
    editorDay: 'Day',
    editorType: 'Run type',
    editorDistance: 'Distance (km)',
    editorDescription: 'Description',
    editorDescriptionPlaceholder: 'Add extra notes for this run...',
    editorNoRun: 'No run on this day.',
    editorExistingRun: 'Current run:',
    editorCreate: 'Add run',
    editorUpdate: 'Update run',
    editorDelete: 'Delete run',
    trainingPlanLabel: 'Training Plan',
    autoGeneratedPlan: 'Automatically generated running plan',
    week: 'Week',
    date: 'Date',
    total: 'Total',
    detailedPlan: 'Detailed plan with explanation',
    from: 'From',
    distance: 'Distance',
    pace: 'Pace',
    noPlanYet: 'No plan yet',
    noPlanHint: 'Fill in your settings on the left and click',
    preview: 'Preview',
    closeModal: 'Close plan modal',
    restDay: 'Rest day',
    unknownPlanningError: 'Planning error',
    invalidStoredPlanRemoved: 'A saved plan had invalid dates and was removed. Generate a new plan.',
    saveFailed: 'Saving failed.',
    loadFailed: 'Loading failed.',
    emptyPlanCreated: 'Empty plan created. You can now fill in your runs manually.',
    exportFailed: 'Export failed.',
    importFailed: 'Import failed.',
    importInvalid: 'Imported file is invalid.',
    generateBeforeExport: 'Generate a plan first.',
    noExportElement: 'No plan element available for export.',
    imageExportFailed: 'Image export failed.',
    pdfExportFailed: 'PDF export failed.',
    generateBeforePrint: 'Generate a plan first to print.',
    fileNameBase: 'training-plan',
    rangeConnector: 'to',
    defaultPlanPrefix: 'Plan',
    savedAtPrefix: 'Saved at',
    raceTypeEasy: 'Easy run',
    raceTypeRecovery: 'Recovery run',
    raceTypeInterval: 'Interval training',
    raceTypeTempo: 'Tempo run',
    raceTypeTempoMarathon: 'Marathon pace',
    raceTypeLong: 'Long run',
    raceTypeRace: 'Race',
  },
  fr: {
    langName: 'Francais',
    appBadge: 'Planificateur Running',
    appTitle: 'Planificateur Marathon & Running',
    appSubtitle: 'Entre ton objectif, la date de course ou le nombre de semaines et recois un plan automatique.',
    settings: 'Parametres',
    language: 'Langue',
    installApp: 'Installer app',
    targetDistance: 'Distance cible',
    customDistance: 'Distance perso (km)',
    customDistancePlaceholder: 'Ex. 15',
    goalTime: 'Temps objectif (hh:mm ou hh:mm:ss)',
    goalTimePlaceholder: '03:45 ou 01:48:30',
    planBasedOn: 'Plan base sur',
    modeDate: 'Date',
    modeWeeks: 'Semaines',
    raceDate: 'Date de course',
    trainingWeeks: 'Semaines d entrainement',
    daysPerWeek: 'Jours d entrainement par semaine',
    daysSuffix: 'jours',
    generatePlan: 'Generer le plan',
    startEmptyPlan: 'Commencer avec calendrier vide',
    reset: 'Reinitialiser',
    savedPlans: 'Plans enregistres',
    savedPlansHint: 'Donne un nom a ton plan et enregistre-le localement pour le rouvrir plus tard.',
    savePlanPlaceholder: 'Ex. Preparation Rotterdam',
    savePlan: 'Enregistrer',
    generateBeforeSave: 'Genere un plan avant de sauvegarder.',
    noSavedPlans: 'Aucun plan enregistre.',
    exportPlanJson: 'Exporter le plan',
    importPlanJson: 'Importer un plan',
    open: 'Ouvrir',
    delete: 'Supprimer',
    planSummary: 'Resume du plan',
    summaryRace: 'Course cible',
    summaryPeriod: 'Periode',
    summaryGoalTime: 'Temps objectif',
    summaryGoalPace: 'Allure cible',
    summaryWeeks: 'Semaines',
    summaryDays: 'Jours par semaine',
    downloadPdf: 'Telecharger PDF',
    downloadImage: 'Telecharger image',
    downloadIcs: 'Telecharger ICS',
    printTable: 'Imprimer tableau',
    printList: 'Imprimer liste',
    printModeCompact: 'Compact (1 page)',
    printModeReadable: 'Lisible (plus grand)',
    showModal: 'Afficher en modal',
    exportPreviewDay: 'Apercu export par jour',
    exportPreviewHint: 'Cette grille hebdo est utilisee pour image, PDF et impression.',
    editorTitle: 'Modifier une sortie par jour',
    editorHint: 'Choisis la semaine et le jour. Tu peux ajouter, modifier type/km ou supprimer.',
    editorWeek: 'Semaine',
    editorDay: 'Jour',
    editorType: 'Type de sortie',
    editorDistance: 'Distance (km)',
    editorDescription: 'Description',
    editorDescriptionPlaceholder: 'Ajoute des notes pour cette sortie...',
    editorNoRun: 'Aucune sortie ce jour.',
    editorExistingRun: 'Sortie actuelle :',
    editorCreate: 'Ajouter',
    editorUpdate: 'Mettre a jour',
    editorDelete: 'Supprimer',
    trainingPlanLabel: 'Plan d entrainement',
    autoGeneratedPlan: 'Plan de course genere automatiquement',
    week: 'Semaine',
    date: 'Date',
    total: 'Total',
    detailedPlan: 'Plan detaille avec explication',
    from: 'Du',
    distance: 'Distance',
    pace: 'Allure',
    noPlanYet: 'Pas encore de plan',
    noPlanHint: 'Complete les parametres a gauche puis clique sur',
    preview: 'Apercu',
    closeModal: 'Fermer la fenetre du plan',
    restDay: 'Repos',
    unknownPlanningError: 'Erreur de planification',
    invalidStoredPlanRemoved: 'Un plan enregistre contenait des dates invalides et a ete supprime. Genere un nouveau plan.',
    saveFailed: 'Echec de sauvegarde.',
    loadFailed: 'Echec de chargement.',
    emptyPlanCreated: 'Plan vide cree. Tu peux maintenant remplir tes sorties manuellement.',
    exportFailed: 'Echec export.',
    importFailed: 'Echec import.',
    importInvalid: 'Le fichier importe est invalide.',
    generateBeforeExport: 'Genere d abord un plan.',
    noExportElement: 'Aucun element de plan disponible pour exporter.',
    imageExportFailed: 'Echec export image.',
    pdfExportFailed: 'Echec export PDF.',
    generateBeforePrint: 'Genere d abord un plan pour imprimer.',
    fileNameBase: 'plan-entrainement',
    rangeConnector: 'au',
    defaultPlanPrefix: 'Plan',
    savedAtPrefix: 'Enregistre le',
    raceTypeEasy: 'Sortie facile',
    raceTypeRecovery: 'Recuperation',
    raceTypeInterval: 'Fractionne',
    raceTypeTempo: 'Tempo',
    raceTypeTempoMarathon: 'Allure marathon',
    raceTypeLong: 'Sortie longue',
    raceTypeRace: 'Course',
  },
} as const

type MessageKey = keyof typeof messages.nl

const localeTag = computed(() => {
  if (currentLocale.value === 'en') return 'en-GB'
  if (currentLocale.value === 'fr') return 'fr-FR'
  return 'nl-NL'
})

const languageOptions: { value: AppLocale; label: string }[] = [
  { value: 'nl', label: 'NL' },
  { value: 'en', label: 'EN' },
  { value: 'fr', label: 'FR' },
]

function t(key: MessageKey) {
  return messages[currentLocale.value][key]
}

const raceOptions = computed<{ label: string; value: RaceType }[]>(() => {
  if (currentLocale.value === 'en') {
    return [
      { label: 'Marathon (42.2 km)', value: 'marathon' },
      { label: 'Half marathon (21.1 km)', value: 'half-marathon' },
      { label: '10 km', value: '10k' },
      { label: '5 km', value: '5k' },
      { label: 'Custom distance', value: 'custom' },
    ]
  }

  if (currentLocale.value === 'fr') {
    return [
      { label: 'Marathon (42.2 km)', value: 'marathon' },
      { label: 'Semi-marathon (21.1 km)', value: 'half-marathon' },
      { label: '10 km', value: '10k' },
      { label: '5 km', value: '5k' },
      { label: 'Distance perso', value: 'custom' },
    ]
  }

  return [
    { label: 'Marathon (42.2 km)', value: 'marathon' },
    { label: 'Halve marathon (21.1 km)', value: 'half-marathon' },
    { label: '10 km', value: '10k' },
    { label: '5 km', value: '5k' },
    { label: 'Eigen afstand', value: 'custom' },
  ]
})

const dayOptions = [2, 3, 4, 5, 6, 7]
const weekdayHeaders = computed(() => {
  if (currentLocale.value === 'en') return ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  if (currentLocale.value === 'fr') return ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim']
  return ['Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za', 'Zo']
})

interface ExportCell {
  title: string
  value: string
  dateLabel: string
  dateISO: string
  type: TrainingSession['type'] | 'rest'
}

interface ExportWeekRow {
  weekNumber: number
  weekEndShort: string
  totalDistanceKm: number
  cells: ExportCell[]
}

type PrintTarget = 'table' | 'list'
type PrintTableMode = 'compact' | 'readable'
const editableSessionTypes: TrainingSession['type'][] = ['easy', 'recovery', 'tempo', 'interval', 'long', 'race']
const selectedWeekNumber = ref<number | null>(null)
const selectedDayIndex = ref(0)
const editType = ref<TrainingSession['type']>('easy')
const editDistanceKm = ref<number>(8)
const editDescription = ref('')
const printTableMode = ref<PrintTableMode>('compact')

const todayISO = computed(() => {
  const now = new Date()
  now.setHours(0, 0, 0, 0)
  return now.toISOString().slice(0, 10)
})

const summaryRows = computed(() => {
  if (!planner.plan) {
    return []
  }

  return [
    { label: t('summaryRace'), value: planner.plan.raceLabel },
    { label: t('summaryPeriod'), value: planDateRange.value },
    { label: t('summaryGoalTime'), value: formatGoalTime(planner.plan.goalTimeMinutes) },
    { label: t('summaryGoalPace'), value: formatPaceValue(planner.plan.targetPaceMinPerKm) },
    { label: t('summaryWeeks'), value: String(planner.plan.totalWeeks) },
    { label: t('summaryDays'), value: String(planner.plan.daysPerWeek) },
  ]
})

const displayError = computed(() => {
  if (localError.value) {
    return localError.value
  }

  if (!planner.lastError) {
    return ''
  }

  if (
    planner.lastError === '__INVALID_STORED_PLAN_ERROR__' ||
    planner.lastError === 'Opgeslagen planning bevatte ongeldige datums en is verwijderd. Genereer een nieuw schema.'
  ) {
    return t('invalidStoredPlanRemoved')
  }

  return planner.lastError
})

const planDateRange = computed(() => {
  if (!planner.plan) {
    return ''
  }
  return `${formatDateLong(planner.plan.startDateISO, currentLocale.value)} ${t('rangeConnector')} ${formatDateLong(planner.plan.endDateISO, currentLocale.value)}`
})

function roundToHalf(value: number) {
  return Math.round(value * 2) / 2
}

function addDays(isoDate: string, days: number) {
  const date = new Date(isoDate)
  date.setDate(date.getDate() + days)
  return date.toISOString().slice(0, 10)
}

function startOfWeekMondayISO(isoDate: string) {
  const date = new Date(isoDate)
  const day = date.getDay()
  const diff = day === 0 ? -6 : 1 - day
  date.setDate(date.getDate() + diff)
  return date.toISOString().slice(0, 10)
}

function formatShortDate(dateISO: string) {
  const date = new Date(dateISO)
  return new Intl.DateTimeFormat(localeTag.value, {
    day: '2-digit',
    month: '2-digit',
  }).format(date)
}

function sessionTypeLabel(type: TrainingSession['type']) {
  if (type === 'easy') return t('raceTypeEasy')
  if (type === 'recovery') return t('raceTypeRecovery')
  if (type === 'interval') return t('raceTypeInterval')
  if (type === 'tempo') return planner.form.raceType === 'marathon' ? t('raceTypeTempoMarathon') : t('raceTypeTempo')
  if (type === 'long') return t('raceTypeLong')
  return t('raceTypeRace')
}

function formatPaceForEdit(minPerKm: number) {
  const minutes = Math.floor(minPerKm)
  const seconds = Math.round((minPerKm - minutes) * 60)
  const normalizedMinutes = seconds === 60 ? minutes + 1 : minutes
  const normalizedSeconds = seconds === 60 ? 0 : seconds
  return `${normalizedMinutes}:${String(normalizedSeconds).padStart(2, '0')} min/km`
}

function paceRangeForEdit(minPerKm: number, fastDelta: number, slowDelta: number) {
  const fast = formatPaceForEdit(Math.max(2.5, minPerKm + fastDelta))
  const slow = formatPaceForEdit(minPerKm + slowDelta)
  return `${fast} - ${slow}`
}

function paceForType(type: TrainingSession['type'], targetPace: number) {
  if (type === 'recovery') return paceRangeForEdit(targetPace, 0.45, 1.25)
  if (type === 'easy' || type === 'long') return paceRangeForEdit(targetPace, 0.3, type === 'long' ? 1.1 : 0.95)
  if (type === 'tempo') return paceRangeForEdit(targetPace, -0.12, 0.22)
  if (type === 'interval') return paceRangeForEdit(targetPace, -0.7, 0.08)
  return formatPaceForEdit(targetPace)
}

function titleForType(type: TrainingSession['type']) {
  if (type === 'race') {
    if (currentLocale.value === 'en') return `Race: ${planner.plan?.raceLabel ?? ''}`.trim()
    if (currentLocale.value === 'fr') return `Course: ${planner.plan?.raceLabel ?? ''}`.trim()
    return `Wedstrijd: ${planner.plan?.raceLabel ?? ''}`.trim()
  }
  return sessionTypeLabel(type)
}

function descriptionForType(type: TrainingSession['type'], distanceKm: number) {
  if (currentLocale.value === 'en') {
    if (type === 'race') return `Race day over ${distanceKm} km. Start controlled and hold your pacing plan.`
    return `${sessionTypeLabel(type)} of ${distanceKm} km.`
  }
  if (currentLocale.value === 'fr') {
    if (type === 'race') return `Jour de course sur ${distanceKm} km. Pars prudemment et respecte ton allure.`
    return `${sessionTypeLabel(type)} de ${distanceKm} km.`
  }
  if (type === 'race') return `Wedstrijddag over ${distanceKm} km. Start beheerst en volg je pacingplan.`
  return `${sessionTypeLabel(type)} van ${distanceKm} km.`
}

function weekdayName(dateISO: string) {
  const date = new Date(dateISO)
  return new Intl.DateTimeFormat(localeTag.value, { weekday: 'long' }).format(date)
}

function roundToHalfValue(value: number) {
  return Math.round(value * 2) / 2
}

function raceLabelForLocale(raceType: RaceType, customDistanceKm: number) {
  if (raceType === 'marathon') return 'Marathon'
  if (raceType === 'half-marathon') return currentLocale.value === 'fr' ? 'Semi-marathon' : currentLocale.value === 'en' ? 'Half Marathon' : 'Halve Marathon'
  if (raceType === '10k') return '10 km'
  if (raceType === '5k') return '5 km'
  if (currentLocale.value === 'en') return `Custom distance (${customDistanceKm} km)`
  if (currentLocale.value === 'fr') return `Distance perso (${customDistanceKm} km)`
  return `Eigen afstand (${customDistanceKm} km)`
}

function raceDistanceFromForm(form: PlannerForm) {
  if (form.raceType === 'marathon') return 42.2
  if (form.raceType === 'half-marathon') return 21.1
  if (form.raceType === '10k') return 10
  if (form.raceType === '5k') return 5
  return roundToHalfValue(Math.max(1, Math.min(100, Number(form.customDistanceKm) || 10)))
}

function parseGoalTimeMinutes(value: string) {
  const cleaned = value.trim()
  if (!cleaned) return null
  const parts = cleaned.split(':').map((part) => Number(part))
  if (parts.some((part) => Number.isNaN(part) || part < 0)) return null
  if (parts.length === 2) {
    const [hours, minutes] = parts
    if (minutes >= 60) return null
    return hours * 60 + minutes
  }
  if (parts.length === 3) {
    const [hours, minutes, seconds] = parts
    if (minutes >= 60 || seconds >= 60) return null
    return hours * 60 + minutes + seconds / 60
  }
  return null
}

function addDaysDate(date: Date, days: number) {
  const next = new Date(date)
  next.setDate(next.getDate() + days)
  return next
}

function startOfWeekMonday(date: Date) {
  const copy = new Date(date)
  const day = copy.getDay()
  const diff = day === 0 ? -6 : 1 - day
  copy.setDate(copy.getDate() + diff)
  copy.setHours(0, 0, 0, 0)
  return copy
}

function formatISO(date: Date) {
  return date.toISOString().slice(0, 10)
}

function buildEmptyPlanFromForm(form: PlannerForm): TrainingPlan {
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const startMonday = startOfWeekMonday(today)

  let totalWeeks = Math.max(2, Math.min(52, Math.round(Number(form.trainingWeeks) || 16)))
  let endDate = addDaysDate(startMonday, totalWeeks * 7 - 1)

  if (form.mode === 'date' && form.raceDate && isValidISODate(form.raceDate)) {
    const raceDate = new Date(form.raceDate)
    raceDate.setHours(0, 0, 0, 0)
    if (raceDate > today) {
      const weekMs = 1000 * 60 * 60 * 24 * 7
      totalWeeks = Math.max(2, Math.min(52, Math.floor((raceDate.getTime() - startMonday.getTime()) / weekMs) + 1))
      endDate = raceDate
    }
  }

  const distanceKm = raceDistanceFromForm(form)
  const parsedGoalTime = parseGoalTimeMinutes(form.goalTime)
  const goalTimeMinutes = parsedGoalTime && parsedGoalTime > 0 ? parsedGoalTime : distanceKm * 6
  const targetPaceMinPerKm = goalTimeMinutes / distanceKm

  const weeks = Array.from({ length: totalWeeks }, (_, index) => {
    const weekNumber = index + 1
    const weekStart = addDaysDate(startMonday, index * 7)
    const weekEnd = addDaysDate(weekStart, 6)
    return {
      weekNumber,
      startDateISO: formatISO(weekStart),
      endDateISO: formatISO(weekEnd),
      focus: '',
      totalDistanceKm: 0,
      sessions: [],
    }
  })

  return {
    raceLabel: raceLabelForLocale(form.raceType, distanceKm),
    distanceKm,
    goalTimeMinutes,
    targetPaceMinPerKm,
    startDateISO: formatISO(today),
    endDateISO: formatISO(endDate),
    totalWeeks,
    daysPerWeek: Math.max(2, Math.min(7, Math.round(Number(form.daysPerWeek) || 4))),
    weeks,
  }
}

function isValidImportedPlan(value: unknown): value is TrainingPlan {
  if (!value || typeof value !== 'object') return false
  const plan = value as TrainingPlan
  if (
    typeof plan.raceLabel !== 'string' ||
    !Number.isFinite(plan.distanceKm) ||
    !Number.isFinite(plan.goalTimeMinutes) ||
    !Number.isFinite(plan.targetPaceMinPerKm) ||
    !isValidISODate(plan.startDateISO) ||
    !isValidISODate(plan.endDateISO) ||
    !Number.isFinite(plan.totalWeeks) ||
    !Number.isFinite(plan.daysPerWeek) ||
    !Array.isArray(plan.weeks)
  ) {
    return false
  }

  return plan.weeks.every((week) => (
    Number.isFinite(week.weekNumber) &&
    isValidISODate(week.startDateISO) &&
    isValidISODate(week.endDateISO) &&
    typeof week.focus === 'string' &&
    Number.isFinite(week.totalDistanceKm) &&
    Array.isArray(week.sessions) &&
    week.sessions.every((session) => (
      typeof session.id === 'string' &&
      isValidISODate(session.dateISO) &&
      typeof session.weekday === 'string' &&
      typeof session.title === 'string' &&
      (session.type === 'easy' || session.type === 'recovery' || session.type === 'tempo' || session.type === 'interval' || session.type === 'long' || session.type === 'race') &&
      Number.isFinite(session.distanceKm) &&
      typeof session.pace === 'string' &&
      typeof session.description === 'string'
    ))
  ))
}

function isValidImportedForm(value: unknown): value is PlannerForm {
  if (!value || typeof value !== 'object') return false
  const form = value as PlannerForm
  return (
    (form.raceType === 'marathon' || form.raceType === 'half-marathon' || form.raceType === '10k' || form.raceType === '5k' || form.raceType === 'custom') &&
    (form.mode === 'date' || form.mode === 'weeks') &&
    Number.isFinite(Number(form.customDistanceKm)) &&
    typeof form.goalTime === 'string' &&
    typeof form.raceDate === 'string' &&
    Number.isFinite(Number(form.trainingWeeks)) &&
    Number.isFinite(Number(form.daysPerWeek))
  )
}

function exportTitle(session: TrainingSession) {
  if (session.type === 'race') {
    return `${t('raceTypeRace')} (${session.weekday})`
  }
  return sessionTypeLabel(session.type)
}

function exportValue(session: TrainingSession) {
  return `${session.distanceKm} km`
}

const exportWeeks = computed<ExportWeekRow[]>(() => {
  if (!planner.plan) {
    return []
  }

  return planner.plan.weeks.map((week) => {
    const sessionsByDate = new Map(week.sessions.map((session) => [session.dateISO, session]))
    const cells: ExportCell[] = []
    let displayedTotalKm = 0
    const raceSession = week.sessions.find((session) => session.type === 'race')

    let gridStartISO = week.startDateISO
    if (raceSession) {
      const weekStartDate = new Date(week.startDateISO)
      const weekEndDate = new Date(addDays(week.startDateISO, 6))
      const raceDate = new Date(raceSession.dateISO)
      const raceInGridRange = raceDate >= weekStartDate && raceDate <= weekEndDate
      if (!raceInGridRange) {
        gridStartISO = startOfWeekMondayISO(raceSession.dateISO)
      }
    }

    for (let dayOffset = 0; dayOffset < 7; dayOffset += 1) {
      const isoDate = addDays(gridStartISO, dayOffset)
      const session = sessionsByDate.get(isoDate)

      if (!session) {
        cells.push({
          title: t('restDay'),
          value: '-',
          dateLabel: formatShortDate(isoDate),
          dateISO: isoDate,
          type: 'rest',
        })
        continue
      }

      cells.push({
        title: exportTitle(session),
        value: exportValue(session),
        dateLabel: formatShortDate(session.dateISO),
        dateISO: session.dateISO,
        type: session.type,
      })
      displayedTotalKm += session.distanceKm
    }

    return {
      weekNumber: week.weekNumber,
      weekEndShort: formatShortDate(addDays(gridStartISO, 6)),
      totalDistanceKm: roundToHalf(displayedTotalKm),
      cells,
    }
  })
})

const sessionTypeOptions = computed(() => editableSessionTypes.map((type) => ({ value: type, label: sessionTypeLabel(type) })))

const selectedExportWeek = computed(() => {
  if (!exportWeeks.value.length) {
    return null
  }

  if (selectedWeekNumber.value == null) {
    return exportWeeks.value[0]
  }

  return exportWeeks.value.find((week) => week.weekNumber === selectedWeekNumber.value) ?? exportWeeks.value[0]
})

const selectedExportCell = computed(() => {
  const week = selectedExportWeek.value
  if (!week) {
    return null
  }

  return week.cells[selectedDayIndex.value] ?? week.cells[0] ?? null
})

const selectedSession = computed(() => {
  const week = selectedExportWeek.value
  const cell = selectedExportCell.value
  if (!week || !cell || !planner.plan) {
    return null
  }

  const sourceWeek = planner.plan.weeks.find((w) => w.weekNumber === week.weekNumber)
  if (!sourceWeek) {
    return null
  }

  return sourceWeek.sessions.find((session) => session.dateISO === cell.dateISO) ?? null
})

function recomputeWeekTotal(weekNumber: number) {
  if (!planner.plan) {
    return
  }
  const week = planner.plan.weeks.find((item) => item.weekNumber === weekNumber)
  if (!week) {
    return
  }
  week.totalDistanceKm = roundToHalf(week.sessions.reduce((sum, session) => sum + session.distanceKm, 0))
}

function applySessionEdit() {
  if (!planner.plan || !selectedExportWeek.value || !selectedExportCell.value) {
    return
  }

  const week = planner.plan.weeks.find((item) => item.weekNumber === selectedExportWeek.value?.weekNumber)
  if (!week) {
    return
  }

  const distanceKm = roundToHalf(Math.max(1, Math.min(100, Number(editDistanceKm.value) || 1)))
  const dateISO = selectedExportCell.value.dateISO
  const existingIndex = week.sessions.findIndex((session) => session.dateISO === dateISO)

  const nextSession: TrainingSession = {
    id: existingIndex >= 0 ? week.sessions[existingIndex].id : `${week.weekNumber}-manual-${Date.now()}`,
    dateISO,
    weekday: weekdayName(dateISO),
    title: titleForType(editType.value),
    type: editType.value,
    distanceKm,
    pace: paceForType(editType.value, planner.plan.targetPaceMinPerKm),
    description: editDescription.value.trim() || descriptionForType(editType.value, distanceKm),
  }

  if (existingIndex >= 0) {
    week.sessions.splice(existingIndex, 1, nextSession)
  } else {
    week.sessions.push(nextSession)
  }

  week.sessions.sort((a, b) => a.dateISO.localeCompare(b.dateISO))
  recomputeWeekTotal(week.weekNumber)
  localError.value = ''
  hasManualEdits.value = true
}

function deleteSessionForSelectedDay() {
  if (!planner.plan || !selectedExportWeek.value || !selectedExportCell.value) {
    return
  }

  const week = planner.plan.weeks.find((item) => item.weekNumber === selectedExportWeek.value?.weekNumber)
  if (!week) {
    return
  }

  const nextSessions = week.sessions.filter((session) => session.dateISO !== selectedExportCell.value?.dateISO)
  if (nextSessions.length === week.sessions.length) {
    return
  }

  week.sessions = nextSessions
  recomputeWeekTotal(week.weekNumber)
  localError.value = ''
  hasManualEdits.value = true
}

async function selectExportCell(weekNumber: number, dayIndex: number) {
  selectedWeekNumber.value = weekNumber
  selectedDayIndex.value = Math.max(0, Math.min(6, dayIndex))

  await nextTick()
  dayEditorElement.value?.scrollIntoView({
    behavior: 'smooth',
    block: 'start',
  })
}

function isSelectedExportCell(weekNumber: number, dayIndex: number) {
  return selectedWeekNumber.value === weekNumber && selectedDayIndex.value === dayIndex
}

function exportCellSession(weekNumber: number, cell: ExportCell) {
  if (!planner.plan || cell.type === 'rest') {
    return null
  }

  const week = planner.plan.weeks.find((item) => item.weekNumber === weekNumber)
  if (!week) {
    return null
  }

  return week.sessions.find((session) => session.dateISO === cell.dateISO) ?? null
}

function exportCellPopoverDescription(weekNumber: number, cell: ExportCell) {
  const session = exportCellSession(weekNumber, cell)
  if (!session) {
    return t('restDay')
  }

  return session.description
}

function exportCellPopoverPace(weekNumber: number, cell: ExportCell) {
  const session = exportCellSession(weekNumber, cell)
  if (!session) {
    return '-'
  }

  return session.pace
}

function setMode(mode: 'date' | 'weeks') {
  planner.form.mode = mode
}

function generatePlan() {
  localError.value = ''

  try {
    planner.generate(currentLocale.value)
    hasManualEdits.value = false
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('unknownPlanningError')
  }
}

function startEmptyPlan() {
  localError.value = ''
  try {
    planner.plan = buildEmptyPlanFromForm(planner.form)
    planner.lastError = ''
    savePlanName.value = ''
    localError.value = t('emptyPlanCreated')
    hasManualEdits.value = true
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('unknownPlanningError')
  }
}

function resetPlanner() {
  planner.reset()
  localError.value = ''
  hasManualEdits.value = false
}

function defaultPlanName() {
  const now = new Intl.DateTimeFormat(localeTag.value, { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date())
  return planner.plan ? `${planner.plan.raceLabel} ${now}` : `${t('defaultPlanPrefix')} ${now}`
}

function saveNamedPlan() {
  localError.value = ''

  try {
    planner.saveCurrentPlan(savePlanName.value.trim() || defaultPlanName(), currentLocale.value)
    savePlanName.value = ''
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('saveFailed')
  }
}

function loadSavedPlanEntry(planId: string) {
  localError.value = ''

  try {
    planner.loadSavedPlan(planId, currentLocale.value)
    planner.generate(currentLocale.value)
    closePreviewModal()
    hasManualEdits.value = false
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('loadFailed')
  }
}

function deleteSavedPlanEntry(planId: string) {
  planner.deleteSavedPlan(planId)
}

function escapeIcsText(value: string) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/\n/g, '\\n')
    .replace(/,/g, '\\,')
    .replace(/;/g, '\\;')
}

function exportCurrentPlanToJson() {
  localError.value = ''
  if (!planner.plan) {
    localError.value = t('generateBeforeExport')
    return
  }

  try {
    const payload = {
      version: 1,
      exportedAtISO: new Date().toISOString(),
      locale: currentLocale.value,
      form: planner.form,
      plan: planner.plan,
    }
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${t('fileNameBase')}-${todayISO.value}.json`
    link.click()
    URL.revokeObjectURL(url)
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('exportFailed')
  }
}

function downloadIcs() {
  localError.value = ''
  if (!planner.plan) {
    localError.value = t('generateBeforeExport')
    return
  }

  try {
    const nowStamp = new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z')
    const events: string[] = []

    planner.plan.weeks.forEach((week) => {
      week.sessions.forEach((session) => {
        const startDate = session.dateISO.replace(/-/g, '')
        const endDate = addDays(session.dateISO, 1).replace(/-/g, '')
        const summary = `${session.title} (${session.distanceKm} km)`
        const description = `${t('pace')}: ${session.pace}\\n${session.description}`

        events.push(
          'BEGIN:VEVENT',
          `UID:${escapeIcsText(`${session.id}-${session.dateISO}@loopschema-planner`)}`,
          `DTSTAMP:${nowStamp}`,
          `DTSTART;VALUE=DATE:${startDate}`,
          `DTEND;VALUE=DATE:${endDate}`,
          `SUMMARY:${escapeIcsText(summary)}`,
          `DESCRIPTION:${escapeIcsText(description)}`,
          `CATEGORIES:${escapeIcsText(sessionTypeLabel(session.type))}`,
          'END:VEVENT',
        )
      })
    })

    const calendar = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//loopschema-planner//training-plan//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      ...events,
      'END:VCALENDAR',
      '',
    ].join('\r\n')

    const blob = new Blob([calendar], { type: 'text/calendar;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${t('fileNameBase')}-${todayISO.value}.ics`
    link.click()
    URL.revokeObjectURL(url)
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('exportFailed')
  }
}

function triggerImportPlan() {
  importFileInput.value?.click()
}

async function handleImportPlanFile(event: Event) {
  localError.value = ''
  const input = event.target as HTMLInputElement
  const file = input.files?.[0]
  if (!file) {
    return
  }

  try {
    const content = await file.text()
    const parsed = JSON.parse(content) as { form?: unknown; plan?: unknown }
    if (!isValidImportedForm(parsed.form) || !isValidImportedPlan(parsed.plan)) {
      throw new Error(t('importInvalid'))
    }

    planner.form = JSON.parse(JSON.stringify(parsed.form))
    planner.plan = JSON.parse(JSON.stringify(parsed.plan))
    planner.lastError = ''
    closePreviewModal()
    hasManualEdits.value = true
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('importFailed')
  } finally {
    input.value = ''
  }
}

function savedPlanPeriod(entry: SavedPlanEntry) {
  return `${formatDateLong(entry.plan.startDateISO, currentLocale.value)} ${t('rangeConnector')} ${formatDateLong(entry.plan.endDateISO, currentLocale.value)}`
}

function savedAtLabel(createdAtISO: string) {
  const date = new Date(createdAtISO)
  if (!Number.isFinite(date.getTime())) {
    return ''
  }

  const label = new Intl.DateTimeFormat(localeTag.value, {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date)

  return `${t('savedAtPrefix')} ${label}`
}

function typeBadgeClass(type: TrainingSession['type']) {
  if (type === 'easy') return 'bg-emerald-100 text-emerald-900'
  if (type === 'recovery') return 'bg-cyan-100 text-cyan-900'
  if (type === 'tempo') return 'bg-amber-100 text-amber-900'
  if (type === 'interval') return 'bg-sky-100 text-sky-900'
  if (type === 'long') return 'bg-violet-100 text-violet-900'
  return 'bg-rose-100 text-rose-900'
}

function exportCellClass(type: ExportCell['type']) {
  if (type === 'easy') return 'bg-emerald-200/75 text-emerald-950'
  if (type === 'recovery') return 'bg-cyan-200/75 text-cyan-950'
  if (type === 'tempo') return 'bg-amber-200/75 text-amber-950'
  if (type === 'interval') return 'bg-sky-200/75 text-sky-950'
  if (type === 'long') return 'bg-violet-200/75 text-violet-950'
  if (type === 'race') return 'bg-rose-300/80 text-rose-950'
  if (type === 'rest') return 'bg-zinc-100 text-zinc-700'
  return ''
}

async function capturePlanCanvas() {
  if (!planner.plan) {
    throw new Error(t('generateBeforeExport'))
  }

  if (!exportElement.value) {
    throw new Error(t('noExportElement'))
  }

  isExporting.value = true
  try {
    return await html2canvas(exportElement.value, {
      scale: 2,
      backgroundColor: '#ffffff',
      useCORS: true,
      scrollX: 0,
      scrollY: -window.scrollY,
    })
  } finally {
    isExporting.value = false
  }
}

async function downloadImage() {
  localError.value = ''

  try {
    const canvas = await capturePlanCanvas()
    const link = document.createElement('a')
    link.download = `${t('fileNameBase')}-${todayISO.value}.png`
    link.href = canvas.toDataURL('image/png')
    link.click()
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('imageExportFailed')
  }
}

async function downloadPdf() {
  localError.value = ''

  try {
    const canvas = await capturePlanCanvas()
    const pdf = new jsPDF('l', 'mm', 'a4')
    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    const margin = 10
    const printableWidth = pageWidth - margin * 2
    const printableHeight = pageHeight - margin * 2

    const imageWidth = printableWidth
    const imageHeight = (canvas.height * imageWidth) / canvas.width
    const imageData = canvas.toDataURL('image/png')

    let remainingHeight = imageHeight
    let yOffset = margin

    pdf.addImage(imageData, 'PNG', margin, yOffset, imageWidth, imageHeight)
    remainingHeight -= printableHeight

    while (remainingHeight > 0) {
      yOffset = margin - (imageHeight - remainingHeight)
      pdf.addPage()
      pdf.addImage(imageData, 'PNG', margin, yOffset, imageWidth, imageHeight)
      remainingHeight -= printableHeight
    }

    pdf.save(`${t('fileNameBase')}-${todayISO.value}.pdf`)
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('pdfExportFailed')
  }
}

function setPrintTargetClass(target: PrintTarget) {
  document.body.classList.remove('print-target-table', 'print-target-list', 'print-table-compact', 'print-table-readable')
  document.body.classList.add(target === 'table' ? 'print-target-table' : 'print-target-list')
  if (target === 'table') {
    document.body.classList.add(printTableMode.value === 'readable' ? 'print-table-readable' : 'print-table-compact')
  }
}

function setTablePrintScale() {
  document.documentElement.style.removeProperty('--print-table-scale')
  if (!exportElement.value) {
    return
  }

  const pxPerMm = 96 / 25.4
  const pageWidthPx = 297 * pxPerMm
  const pageHeightPx = 210 * pxPerMm
  const marginMm = 4
  const availableWidth = pageWidthPx - marginMm * 2 * pxPerMm
  const availableHeight = pageHeightPx - marginMm * 2 * pxPerMm

  const contentWidth = exportElement.value.scrollWidth
  const contentHeight = exportElement.value.scrollHeight

  if (!contentWidth || !contentHeight) {
    return
  }

  const scaleByWidth = availableWidth / contentWidth
  const scaleByHeight = availableHeight / contentHeight
  const scale = Math.min(1, scaleByWidth, scaleByHeight)
  const baseScale = Math.max(0.18, Number.isFinite(scale) ? scale : 1)
  const modeAdjustedScale = printTableMode.value === 'readable' ? Math.min(1, baseScale * 1.2) : baseScale

  document.documentElement.style.setProperty('--print-table-scale', String(modeAdjustedScale))
}

function clearPrintTargetClass() {
  document.body.classList.remove('print-target-table', 'print-target-list', 'print-table-compact', 'print-table-readable')
  document.documentElement.style.removeProperty('--print-table-scale')
}

async function printPlan(target: PrintTarget) {
  if (!planner.plan) {
    localError.value = t('generateBeforePrint')
    return
  }

  if (isPreviewModalOpen.value) {
    closePreviewModal()
  }

  setPrintTargetClass(target)
  await nextTick()
  if (target === 'table') {
    setTablePrintScale()
  }
  window.print()
}

function openPreviewModal() {
  if (!planner.plan) {
    return
  }
  isPreviewModalOpen.value = true
}

function closePreviewModal() {
  isPreviewModalOpen.value = false
}

function handleWindowKeydown(event: KeyboardEvent) {
  if (event.key === 'Escape') {
    closePreviewModal()
  }
}

function handlePopState() {
  const locale = getLocaleFromUrl()
  if (locale !== currentLocale.value) {
    currentLocale.value = locale
  }
}

function handleBeforeInstallPrompt(event: Event) {
  const installEvent = event as BeforeInstallPromptEvent
  installEvent.preventDefault()
  deferredInstallPrompt.value = installEvent
  canInstallPwa.value = true
}

function handleAppInstalled() {
  isAppInstalled.value = true
  canInstallPwa.value = false
  deferredInstallPrompt.value = null
}

async function installPwa() {
  if (!deferredInstallPrompt.value) {
    return
  }

  await deferredInstallPrompt.value.prompt()
  const choiceResult = await deferredInstallPrompt.value.userChoice
  if (choiceResult.outcome !== 'accepted') {
    return
  }

  canInstallPwa.value = false
  deferredInstallPrompt.value = null
}

watch(isPreviewModalOpen, (open) => {
  document.body.classList.toggle('modal-open', open)
})

watch(exportWeeks, (weeks) => {
  if (!weeks.length) {
    selectedWeekNumber.value = null
    selectedDayIndex.value = 0
    return
  }

  if (selectedWeekNumber.value == null || !weeks.some((week) => week.weekNumber === selectedWeekNumber.value)) {
    selectedWeekNumber.value = weeks[0].weekNumber
  }

  if (selectedDayIndex.value < 0 || selectedDayIndex.value > 6) {
    selectedDayIndex.value = 0
  }
}, { immediate: true })

watch(selectedSession, (session) => {
  if (session) {
    editType.value = session.type
    editDistanceKm.value = session.distanceKm
    editDescription.value = session.description
    return
  }

  editType.value = 'easy'
  editDistanceKm.value = 8
  editDescription.value = ''
}, { immediate: true })

watch(currentLocale, (locale, previousLocale) => {
  document.documentElement.lang = locale
  syncLocaleInUrl(locale, !previousLocale)

  if (planner.plan && !hasManualEdits.value) {
    try {
      planner.generate(locale)
      localError.value = ''
    } catch (error) {
      localError.value = error instanceof Error ? error.message : t('unknownPlanningError')
    }
  }
})

onMounted(() => {
  document.documentElement.lang = currentLocale.value
  syncLocaleInUrl(currentLocale.value, true)
  isAppInstalled.value =
    window.matchMedia('(display-mode: standalone)').matches ||
    (typeof navigator !== 'undefined' && 'standalone' in navigator && Boolean((navigator as Navigator & { standalone?: boolean }).standalone))
  canInstallPwa.value = false
  window.addEventListener('keydown', handleWindowKeydown)
  window.addEventListener('afterprint', clearPrintTargetClass)
  window.addEventListener('popstate', handlePopState)
  window.addEventListener('beforeinstallprompt', handleBeforeInstallPrompt)
  window.addEventListener('appinstalled', handleAppInstalled)
})

onBeforeUnmount(() => {
  document.body.classList.remove('modal-open')
  clearPrintTargetClass()
  window.removeEventListener('keydown', handleWindowKeydown)
  window.removeEventListener('afterprint', clearPrintTargetClass)
  window.removeEventListener('popstate', handlePopState)
  window.removeEventListener('beforeinstallprompt', handleBeforeInstallPrompt)
  window.removeEventListener('appinstalled', handleAppInstalled)
})
</script>

<template>
  <main class="min-h-screen bg-background pb-12">
    <div class="mx-auto max-w-[1800px] px-4 py-8 sm:px-6 lg:px-8">
      <header class="hero-shell mb-7 rounded-3xl px-6 py-8 md:px-8 md:py-10">
        <div class="flex flex-wrap items-center justify-between gap-3">
          <p class="inline-flex items-center gap-2 rounded-full bg-muted/80 px-3 py-1 text-xs font-semibold uppercase tracking-[0.14em] text-foreground backdrop-blur">
            <Goal class="h-4 w-4" />
            {{ t('appBadge') }}
          </p>
          <div class="flex items-center gap-2">
            <Button
              v-if="canInstallPwa && !isAppInstalled"
              type="button"
              class="install-btn h-9 px-3 text-xs"
              @click="installPwa"
            >
              <span class="install-btn-icon">
                <Download class="h-3.5 w-3.5" />
              </span>
              {{ t('installApp') }}
            </Button>
            <select
              v-model="currentLocale"
              class="h-9 rounded-lg border border-border bg-white px-3 text-xs font-semibold uppercase outline-none transition focus:border-zinc-500 focus:ring-2 focus:ring-zinc-300"
            >
              <option v-for="option in languageOptions" :key="option.value" :value="option.value">{{ option.label }}</option>
            </select>
          </div>
        </div>
        <h1 class="mt-3 text-2xl font-bold text-foreground md:text-3xl">{{ t('appTitle') }}</h1>
        <p class="mt-4 max-w-3xl text-sm font-semibold leading-relaxed text-muted-foreground md:text-base">
          {{ t('appSubtitle') }}
        </p>
      </header>

      <div class="grid items-start gap-6 lg:grid-cols-[380px,minmax(0,1fr)] print:block">
        <Card class="h-fit p-5 print:hidden lg:sticky lg:top-6">
          <h2 class="mb-4 text-xl font-semibold">{{ t('settings') }}</h2>

          <div class="space-y-4">
            <div>
              <Label>{{ t('targetDistance') }}</Label>
              <select
                v-model="planner.form.raceType"
                class="h-10 w-full rounded-xl border border-border bg-white px-3 text-sm font-medium outline-none transition focus:border-zinc-500 focus:ring-2 focus:ring-zinc-300"
              >
                <option v-for="option in raceOptions" :key="option.value" :value="option.value">
                  {{ option.label }}
                </option>
              </select>
            </div>

            <div v-if="planner.form.raceType === 'custom'">
              <Label>{{ t('customDistance') }}</Label>
              <Input
                :model-value="planner.form.customDistanceKm"
                type="number"
                min="1"
                max="100"
                step="0.5"
                :placeholder="t('customDistancePlaceholder')"
                @update:model-value="planner.form.customDistanceKm = Number($event)"
              />
            </div>

            <div>
              <Label>{{ t('goalTime') }}</Label>
              <Input v-model="planner.form.goalTime" :placeholder="t('goalTimePlaceholder')" />
            </div>

            <div>
              <Label>{{ t('planBasedOn') }}</Label>
              <div class="grid grid-cols-2 gap-2">
                <Button
                  type="button"
                  :variant="planner.form.mode === 'date' ? 'default' : 'outline'"
                  class="w-full"
                  @click="setMode('date')"
                >
                  <Calendar class="h-4 w-4" />
                  {{ t('modeDate') }}
                </Button>
                <Button
                  type="button"
                  :variant="planner.form.mode === 'weeks' ? 'default' : 'outline'"
                  class="w-full"
                  @click="setMode('weeks')"
                >
                  <RefreshCcw class="h-4 w-4" />
                  {{ t('modeWeeks') }}
                </Button>
              </div>
            </div>

            <div v-if="planner.form.mode === 'date'">
              <Label>{{ t('raceDate') }}</Label>
              <Input v-model="planner.form.raceDate" type="date" :min="todayISO" />
            </div>

            <div v-else>
              <Label>{{ t('trainingWeeks') }}</Label>
              <Input
                :model-value="planner.form.trainingWeeks"
                type="number"
                min="2"
                max="52"
                step="1"
                @update:model-value="planner.form.trainingWeeks = Number($event)"
              />
            </div>

            <div>
              <Label>{{ t('daysPerWeek') }}</Label>
              <select
                v-model.number="planner.form.daysPerWeek"
                class="h-10 w-full rounded-xl border border-border bg-white px-3 text-sm font-medium outline-none transition focus:border-zinc-500 focus:ring-2 focus:ring-zinc-300"
              >
                <option v-for="days in dayOptions" :key="days" :value="days">{{ days }} {{ t('daysSuffix') }}</option>
              </select>
            </div>

            <div class="grid grid-cols-1 gap-2 pt-1">
              <Button type="button" size="lg" @click="generatePlan">{{ t('generatePlan') }}</Button>
              <Button type="button" variant="outline" @click="startEmptyPlan">{{ t('startEmptyPlan') }}</Button>
              <Button type="button" variant="secondary" @click="resetPlanner">{{ t('reset') }}</Button>
            </div>

            <p v-if="displayError" class="rounded-lg bg-zinc-200 px-3 py-2 text-sm text-zinc-900">
              {{ displayError }}
            </p>
          </div>
        </Card>

        <section>
          <Card class="mb-4 overflow-hidden border-zinc-300/90 bg-gradient-to-br from-zinc-50 to-white p-5 shadow-[0_12px_36px_-26px_rgba(24,24,27,0.65)] print:hidden">
            <div class="mb-3 flex flex-wrap items-center justify-between gap-2">
              <h2 class="text-2xl font-bold">{{ t('savedPlans') }}</h2>
              <span class="rounded-full bg-zinc-900 px-3 py-1 text-xs font-bold text-white">
                {{ planner.savedPlans.length }}
              </span>
            </div>
            <p class="text-sm font-semibold text-zinc-600">
              {{ t('savedPlansHint') }}
            </p>

            <div class="mt-4 grid gap-2 sm:grid-cols-[1fr,auto]">
              <Input
                v-model="savePlanName"
                :disabled="!planner.plan"
                :placeholder="t('savePlanPlaceholder')"
                @keydown.enter.prevent="saveNamedPlan"
              />
              <Button type="button" :disabled="!planner.plan" @click="saveNamedPlan">
                <Save class="h-4 w-4" />
                {{ t('savePlan') }}
              </Button>
            </div>

            <div class="mt-2 flex flex-wrap gap-2">
              <Button type="button" size="sm" variant="outline" :disabled="!planner.plan" @click="exportCurrentPlanToJson">
                <Download class="h-4 w-4" />
                {{ t('exportPlanJson') }}
              </Button>
              <Button type="button" size="sm" variant="outline" @click="triggerImportPlan">
                <FolderOpen class="h-4 w-4" />
                {{ t('importPlanJson') }}
              </Button>
              <input
                ref="importFileInput"
                type="file"
                accept="application/json,.json"
                class="hidden"
                @change="handleImportPlanFile"
              />
            </div>

            <p v-if="!planner.plan" class="mt-2 text-xs font-medium text-muted-foreground">
              {{ t('generateBeforeSave') }}
            </p>

            <div class="mt-4 space-y-2">
              <p v-if="!planner.savedPlans.length" class="rounded-lg border border-dashed border-zinc-400/70 bg-zinc-100 px-3 py-2 text-sm font-medium text-zinc-600">
                {{ t('noSavedPlans') }}
              </p>

              <article
                v-for="saved in planner.savedPlans"
                :key="saved.id"
                class="flex flex-col gap-3 rounded-xl border border-zinc-300/80 bg-white px-3 py-3 shadow-[0_12px_26px_-24px_rgba(24,24,27,0.8)] transition hover:-translate-y-[1px] hover:border-zinc-400 sm:flex-row sm:items-start sm:justify-between"
              >
                <div class="min-w-0">
                  <h3 class="truncate text-sm font-bold text-zinc-900">{{ saved.name }}</h3>
                  <p class="text-xs font-semibold text-zinc-700">{{ saved.plan.raceLabel }} · {{ savedPlanPeriod(saved) }}</p>
                  <p class="text-xs text-zinc-500">{{ savedAtLabel(saved.createdAtISO) }}</p>
                </div>
                <div class="flex shrink-0 gap-2">
                  <Button type="button" size="sm" class="bg-zinc-900 text-white hover:brightness-110" @click="loadSavedPlanEntry(saved.id)">
                    <FolderOpen class="h-3.5 w-3.5" />
                    {{ t('open') }}
                  </Button>
                  <Button
                    type="button"
                    size="sm"
                    variant="ghost"
                    class="text-zinc-700 hover:bg-rose-100 hover:text-rose-700"
                    @click="deleteSavedPlanEntry(saved.id)"
                  >
                    <Trash2 class="h-3.5 w-3.5" />
                    {{ t('delete') }}
                  </Button>
                </div>
              </article>
            </div>
          </Card>

          <Card v-if="planner.plan" class="mb-4 p-5 print:hidden">
            <h2 class="mb-3 text-2xl font-bold">{{ t('planSummary') }}</h2>
            <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
              <div v-for="row in summaryRows" :key="row.label" class="rounded-xl border border-border/70 bg-secondary/60 px-3 py-2">
                <p class="text-xs uppercase tracking-[0.11em] text-muted-foreground">{{ row.label }}</p>
                <p class="text-sm font-semibold text-foreground">{{ row.value }}</p>
              </div>
            </div>

            <div class="mt-4 flex flex-wrap gap-2">
              <div class="inline-flex rounded-xl border border-border bg-white p-1">
                <button
                  type="button"
                  class="rounded-lg px-2.5 py-1 text-xs font-semibold transition"
                  :class="printTableMode === 'compact' ? 'bg-zinc-900 text-white' : 'text-zinc-700 hover:bg-zinc-100'"
                  @click="printTableMode = 'compact'"
                >
                  {{ t('printModeCompact') }}
                </button>
                <button
                  type="button"
                  class="rounded-lg px-2.5 py-1 text-xs font-semibold transition"
                  :class="printTableMode === 'readable' ? 'bg-zinc-900 text-white' : 'text-zinc-700 hover:bg-zinc-100'"
                  @click="printTableMode = 'readable'"
                >
                  {{ t('printModeReadable') }}
                </button>
              </div>
              <Button type="button" variant="outline" :disabled="isExporting" @click="downloadPdf">
                <FileText class="h-4 w-4" />
                {{ t('downloadPdf') }}
              </Button>
              <Button type="button" variant="outline" :disabled="isExporting" @click="downloadImage">
                <FileImage class="h-4 w-4" />
                {{ t('downloadImage') }}
              </Button>
              <Button type="button" variant="outline" @click="downloadIcs">
                <Calendar class="h-4 w-4" />
                {{ t('downloadIcs') }}
              </Button>
              <Button type="button" variant="secondary" @click="printPlan('table')">
                <Printer class="h-4 w-4" />
                {{ t('printTable') }}
              </Button>
              <Button type="button" variant="outline" @click="printPlan('list')">
                <Printer class="h-4 w-4" />
                {{ t('printList') }}
              </Button>
              <Button type="button" variant="outline" @click="openPreviewModal">
                <Expand class="h-4 w-4" />
                {{ t('showModal') }}
              </Button>
            </div>
          </Card>

          <Card v-if="planner.plan" id="printable-plan-section" class="mb-4 hidden p-4 md:block print:block">
            <div class="mb-3 print:hidden">
              <h2 class="text-2xl font-bold">{{ t('exportPreviewDay') }}</h2>
              <p class="text-sm font-medium text-muted-foreground">
                {{ t('exportPreviewHint') }}
              </p>
            </div>

            <div class="overflow-hidden rounded-xl border border-border/90 bg-white/80">
              <div id="printable-plan" ref="exportElement" class="export-sheet">
                <header class="export-sheet-header">
                  <h3>{{ planner.plan.raceLabel }} {{ t('trainingPlanLabel') }} · {{ planDateRange }}</h3>
                  <p>{{ t('autoGeneratedPlan') }}</p>
                </header>

                <table class="export-table">
                  <thead>
                    <tr>
                      <th class="week-col">{{ t('week') }}</th>
                      <th v-for="day in weekdayHeaders" :key="day">{{ day }}</th>
                      <th class="date-col">{{ t('date') }}</th>
                      <th class="km-col">{{ t('total') }}</th>
                    </tr>
                  </thead>
                  <tbody>
                    <template v-for="week in exportWeeks" :key="week.weekNumber">
                      <tr class="separator-row">
                        <td colspan="10" />
                      </tr>
                      <tr class="week-row">
                        <td class="week-number">{{ week.weekNumber }}.</td>
                        <td
                          v-for="(cell, cellIndex) in week.cells"
                          :key="`${week.weekNumber}-${cellIndex}`"
                          :class="[
                            'day-cell group relative cursor-pointer transition',
                            isSelectedExportCell(week.weekNumber, cellIndex) ? 'ring-2 ring-blue-500 ring-inset bg-blue-50/35' : 'hover:bg-blue-50/25',
                          ]"
                          @click="selectExportCell(week.weekNumber, cellIndex)"
                        >
                          <div class="cell-title">{{ cell.title }}</div>
                          <div class="cell-date">{{ cell.dateLabel }}</div>
                          <div :class="['cell-value', exportCellClass(cell.type)]">{{ cell.value }}</div>
                          <div
                            class="pointer-events-none invisible absolute left-1/2 top-full z-30 mt-1 w-64 -translate-x-1/2 rounded-lg border border-zinc-300 bg-white/95 p-2 text-left opacity-0 shadow-lg transition group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100"
                          >
                            <p class="text-[11px] font-bold text-zinc-900">{{ cell.title }} · {{ cell.value }}</p>
                            <p class="mt-1 text-[10px] font-semibold text-zinc-700">{{ t('pace') }}: {{ exportCellPopoverPace(week.weekNumber, cell) }}</p>
                            <p class="mt-1 text-[10px] leading-snug text-zinc-700">{{ exportCellPopoverDescription(week.weekNumber, cell) }}</p>
                          </div>
                        </td>
                        <td class="week-end-date">{{ week.weekEndShort }}</td>
                        <td class="week-km">{{ week.totalDistanceKm }} km</td>
                      </tr>
                    </template>
                    <tr class="separator-row">
                      <td colspan="10" />
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div ref="dayEditorElement" class="print-no-table mt-4 rounded-xl border border-border/80 bg-white/80 p-4 print:hidden">
              <h3 class="text-sm font-bold uppercase tracking-[0.08em] text-foreground">{{ t('editorTitle') }}</h3>
              <p class="mt-1 text-xs text-muted-foreground">{{ t('editorHint') }}</p>

              <div class="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
                <div>
                  <Label>{{ t('editorWeek') }}</Label>
                  <select
                    v-model.number="selectedWeekNumber"
                    class="h-10 w-full rounded-xl border border-border bg-white px-3 text-sm font-medium outline-none transition focus:border-zinc-500 focus:ring-2 focus:ring-zinc-300"
                  >
                    <option v-for="week in exportWeeks" :key="`edit-week-${week.weekNumber}`" :value="week.weekNumber">
                      {{ t('week') }} {{ week.weekNumber }}
                    </option>
                  </select>
                </div>

                <div>
                  <Label>{{ t('editorDay') }}</Label>
                  <select
                    v-model.number="selectedDayIndex"
                    class="h-10 w-full rounded-xl border border-border bg-white px-3 text-sm font-medium outline-none transition focus:border-zinc-500 focus:ring-2 focus:ring-zinc-300"
                  >
                    <option
                      v-for="(cell, idx) in selectedExportWeek ? selectedExportWeek.cells : []"
                      :key="`edit-day-${idx}`"
                      :value="idx"
                    >
                      {{ weekdayHeaders[idx] }} · {{ cell.dateLabel }}
                    </option>
                  </select>
                </div>

                <div>
                  <Label>{{ t('editorType') }}</Label>
                  <select
                    v-model="editType"
                    class="h-10 w-full rounded-xl border border-border bg-white px-3 text-sm font-medium outline-none transition focus:border-zinc-500 focus:ring-2 focus:ring-zinc-300"
                  >
                    <option v-for="option in sessionTypeOptions" :key="`edit-type-${option.value}`" :value="option.value">
                      {{ option.label }}
                    </option>
                  </select>
                </div>

                <div>
                  <Label>{{ t('editorDistance') }}</Label>
                  <Input
                    :model-value="editDistanceKm"
                    type="number"
                    min="1"
                    max="100"
                    step="0.5"
                    @update:model-value="editDistanceKm = Number($event)"
                  />
                </div>
              </div>

              <div class="mt-3">
                <Label>{{ t('editorDescription') }}</Label>
                <textarea
                  v-model="editDescription"
                  rows="3"
                  class="w-full rounded-xl border border-border bg-white px-3 py-2 text-sm outline-none transition focus:border-zinc-500 focus:ring-2 focus:ring-zinc-300"
                  :placeholder="t('editorDescriptionPlaceholder')"
                />
              </div>

              <p class="mt-3 text-xs text-muted-foreground">
                <template v-if="selectedSession">
                  {{ t('editorExistingRun') }} <strong>{{ sessionTypeLabel(selectedSession.type) }}</strong> · {{ selectedSession.distanceKm }} km
                </template>
                <template v-else>
                  {{ t('editorNoRun') }}
                </template>
              </p>

              <div class="mt-3 flex flex-wrap gap-2">
                <Button type="button" size="sm" @click="applySessionEdit">
                  {{ selectedSession ? t('editorUpdate') : t('editorCreate') }}
                </Button>
                <Button type="button" size="sm" variant="outline" :disabled="!selectedSession" @click="deleteSessionForSelectedDay">
                  {{ t('editorDelete') }}
                </Button>
              </div>
            </div>
          </Card>

          <Card v-if="planner.plan" id="printable-list-section" class="p-5">
            <div class="mb-5 border-b border-border pb-4">
              <h2 class="text-3xl font-bold">{{ t('detailedPlan') }}</h2>
              <p class="mt-2 text-sm font-medium text-muted-foreground">
                {{ t('from') }} {{ planDateRange }}
              </p>
            </div>

            <div class="space-y-4">
              <article
                v-for="week in planner.plan.weeks"
                :key="week.weekNumber"
                class="animate-rise rounded-xl border border-border bg-white p-4"
                :style="{ animationDelay: `${week.weekNumber * 40}ms` }"
              >
                <div class="mb-3 flex flex-wrap items-center justify-between gap-3">
                  <div>
                    <h3 class="text-lg font-semibold">{{ t('week') }} {{ week.weekNumber }}</h3>
                    <p class="text-sm text-muted-foreground">
                      {{ formatDateLong(week.startDateISO, currentLocale) }} - {{ formatDateLong(week.endDateISO, currentLocale) }}
                    </p>
                  </div>
                  <span class="rounded-full bg-secondary px-3 py-1 text-xs font-semibold">{{ week.totalDistanceKm }} km</span>
                </div>

                <p class="mb-3 rounded-lg bg-muted px-3 py-2 text-sm text-muted-foreground">{{ week.focus }}</p>

                <div class="space-y-2">
                  <div
                    v-for="session in week.sessions"
                    :key="session.id"
                    class="rounded-lg border border-border/70 bg-card p-3"
                  >
                    <div class="mb-1 flex flex-wrap items-center justify-between gap-2">
                      <p class="font-semibold text-foreground">
                        {{ session.weekday }} {{ formatDateLong(session.dateISO, currentLocale) }} - {{ session.title }}
                      </p>
                      <span :class="['rounded-full px-2.5 py-1 text-xs font-semibold capitalize', typeBadgeClass(session.type)]">
                        {{ sessionTypeLabel(session.type) }}
                      </span>
                    </div>
                    <p class="mb-1 text-sm text-foreground">
                      <strong>{{ t('distance') }}:</strong> {{ session.distanceKm }} km · <strong>{{ t('pace') }}:</strong> {{ session.pace }}
                    </p>
                    <p class="text-sm text-muted-foreground">{{ session.description }}</p>
                  </div>
                </div>
              </article>
            </div>
          </Card>

          <Card v-else class="grid min-h-80 place-items-center p-8 text-center">
            <div>
              <Download class="mx-auto mb-3 h-8 w-8 text-muted-foreground" />
              <h2 class="text-2xl font-bold">{{ t('noPlanYet') }}</h2>
              <p class="mt-2 text-sm text-muted-foreground">
                {{ t('noPlanHint') }} <strong>{{ t('generatePlan') }}</strong>.
              </p>
            </div>
          </Card>
        </section>
      </div>
    </div>

    <Teleport to="body">
      <div v-if="isPreviewModalOpen" class="modal-overlay">
        <button class="modal-backdrop" :aria-label="t('closeModal')" @click="closePreviewModal" />
        <section class="modal-panel">
          <header class="modal-panel-header">
            <div>
              <p class="text-[11px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">{{ t('preview') }}</p>
              <h3 class="text-base font-bold text-foreground md:text-lg">
                {{ planner.plan?.raceLabel }} {{ t('trainingPlanLabel') }}
              </h3>
              <p class="text-sm font-medium text-muted-foreground">{{ planDateRange }}</p>
            </div>
            <Button type="button" variant="ghost" class="h-9 w-9 rounded-full p-0" @click="closePreviewModal">
              <X class="h-4 w-4" />
            </Button>
          </header>

          <div class="modal-panel-body">
            <div class="overflow-hidden rounded-xl border border-border/90 bg-white/80">
              <div class="export-sheet">
                <header class="export-sheet-header">
                  <h3>{{ planner.plan?.raceLabel }} {{ t('trainingPlanLabel') }} · {{ planDateRange }}</h3>
                  <p>{{ t('autoGeneratedPlan') }}</p>
                </header>

                <table class="export-table">
                  <thead>
                    <tr>
                      <th class="week-col">{{ t('week') }}</th>
                      <th v-for="day in weekdayHeaders" :key="`modal-${day}`">{{ day }}</th>
                      <th class="date-col">{{ t('date') }}</th>
                      <th class="km-col">{{ t('total') }}</th>
                    </tr>
                  </thead>
                  <tbody>
                    <template v-for="week in exportWeeks" :key="`modal-${week.weekNumber}`">
                      <tr class="separator-row">
                        <td colspan="10" />
                      </tr>
                      <tr class="week-row">
                        <td class="week-number">{{ week.weekNumber }}.</td>
                        <td
                          v-for="(cell, cellIndex) in week.cells"
                          :key="`modal-${week.weekNumber}-${cellIndex}`"
                          class="day-cell group relative"
                        >
                          <div class="cell-title">{{ cell.title }}</div>
                          <div class="cell-date">{{ cell.dateLabel }}</div>
                          <div :class="['cell-value', exportCellClass(cell.type)]">{{ cell.value }}</div>
                          <div
                            class="pointer-events-none invisible absolute left-1/2 top-full z-30 mt-1 w-64 -translate-x-1/2 rounded-lg border border-zinc-300 bg-white/95 p-2 text-left opacity-0 shadow-lg transition group-hover:visible group-hover:opacity-100"
                          >
                            <p class="text-[11px] font-bold text-zinc-900">{{ cell.title }} · {{ cell.value }}</p>
                            <p class="mt-1 text-[10px] font-semibold text-zinc-700">{{ t('pace') }}: {{ exportCellPopoverPace(week.weekNumber, cell) }}</p>
                            <p class="mt-1 text-[10px] leading-snug text-zinc-700">{{ exportCellPopoverDescription(week.weekNumber, cell) }}</p>
                          </div>
                        </td>
                        <td class="week-end-date">{{ week.weekEndShort }}</td>
                        <td class="week-km">{{ week.totalDistanceKm }} km</td>
                      </tr>
                    </template>
                    <tr class="separator-row">
                      <td colspan="10" />
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </section>
      </div>
    </Teleport>
  </main>
</template>
