<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'
import { Calendar, Download, Expand, FileImage, FileText, FolderOpen, Goal, Printer, RefreshCcw, Save, Trash2, X } from 'lucide-vue-next'
import Button from '@/components/ui/Button.vue'
import Card from '@/components/ui/Card.vue'
import Input from '@/components/ui/Input.vue'
import Label from '@/components/ui/Label.vue'
import { getLocaleFromUrl, syncLocaleInUrl } from '@/lib/i18n'
import { formatDateLong, formatGoalTime, formatPaceValue } from '@/lib/planner'
import { usePlannerStore } from '@/stores/planner'
import type { AppLocale, RaceType, SavedPlanEntry, TrainingSession } from '@/types/planner'

const planner = usePlannerStore()
const exportElement = ref<HTMLElement | null>(null)
const localError = ref('')
const isExporting = ref(false)
const isPreviewModalOpen = ref(false)
const savePlanName = ref('')
const currentLocale = ref<AppLocale>(getLocaleFromUrl())

const messages = {
  nl: {
    langName: 'Nederlands',
    appBadge: 'Training Planner',
    appTitle: 'Marathon & Running Planner',
    appSubtitle: 'Vul je doeltijd, wedstrijddatum of aantal trainingsweken in en krijg automatisch een planning.',
    settings: 'Instellingen',
    language: 'Taal',
    targetDistance: 'Doelafstand',
    customDistance: 'Eigen afstand (km)',
    customDistancePlaceholder: 'Bijv. 15',
    goalTime: 'Doeltijd (uu:mm of uu:mm:ss)',
    goalTimePlaceholder: '03:45 of 01:48:30',
    planBasedOn: 'Plan op basis van',
    modeDate: 'Datum',
    modeWeeks: 'Weken',
    raceDate: 'Wedstrijddatum',
    trainingWeeks: 'Aantal trainingsweken',
    daysPerWeek: 'Trainingsdagen per week',
    daysSuffix: 'dagen',
    generatePlan: 'Planning genereren',
    reset: 'Reset',
    savedPlans: 'Opgeslagen planningen',
    savedPlansHint: 'Geef je planning een naam en bewaar hem lokaal om later opnieuw te openen.',
    savePlanPlaceholder: 'Bijv. Rotterdam voorbereiding',
    savePlan: 'Planning opslaan',
    generateBeforeSave: 'Genereer eerst een planning om op te slaan.',
    noSavedPlans: 'Nog geen opgeslagen planningen.',
    open: 'Open',
    delete: 'Verwijder',
    planSummary: 'Planoverzicht',
    summaryRace: 'Doelrace',
    summaryPeriod: 'Periode',
    summaryGoalTime: 'Doeltijd',
    summaryGoalPace: 'Doeltempo',
    summaryWeeks: 'Trainingsweken',
    summaryDays: 'Dagen per week',
    downloadPdf: 'Download PDF',
    downloadImage: 'Download afbeelding',
    printTable: 'Afdruk tabel',
    printList: 'Afdruk lijst',
    showModal: 'Toon in modal',
    exportPreviewDay: 'Exportvoorbeeld per dag',
    exportPreviewHint: 'Dit weekrooster wordt gebruikt voor afbeelding, PDF en print.',
    trainingPlanLabel: 'Trainingsplanning',
    autoGeneratedPlan: 'Automatisch gegenereerd loopschema',
    week: 'Week',
    date: 'Datum',
    total: 'Totaal',
    detailedPlan: 'Detailplanning met uitleg',
    from: 'Van',
    distance: 'Afstand',
    pace: 'Tempo',
    noPlanYet: 'Nog geen planning',
    noPlanHint: 'Vul links je instellingen in en klik op',
    preview: 'Preview',
    closeModal: 'Sluit schema modal',
    restDay: 'Rustdag',
    unknownPlanningError: 'Planningsfout',
    invalidStoredPlanRemoved: 'Opgeslagen planning bevatte ongeldige datums en is verwijderd. Genereer een nieuw schema.',
    saveFailed: 'Opslaan mislukt.',
    loadFailed: 'Laden mislukt.',
    generateBeforeExport: 'Genereer eerst een planning.',
    noExportElement: 'Geen planningselement beschikbaar om te exporteren.',
    imageExportFailed: 'Export naar afbeelding mislukt.',
    pdfExportFailed: 'Export naar PDF mislukt.',
    generateBeforePrint: 'Genereer eerst een planning om te kunnen printen.',
    fileNameBase: 'trainingsplan',
    rangeConnector: 't/m',
    defaultPlanPrefix: 'Planning',
    savedAtPrefix: 'Opgeslagen op',
    raceTypeEasy: 'Rustige duurloop',
    raceTypeRecovery: 'Herstelrun',
    raceTypeInterval: 'Interval training',
    raceTypeTempo: 'Tempo run',
    raceTypeTempoMarathon: 'Marathon tempo',
    raceTypeLong: 'Lange duurloop',
    raceTypeRace: 'Wedstrijd',
  },
  en: {
    langName: 'English',
    appBadge: 'Training Planner',
    appTitle: 'Marathon & Running Planner',
    appSubtitle: 'Enter your goal time, race date or number of training weeks and get an automatic plan.',
    settings: 'Settings',
    language: 'Language',
    targetDistance: 'Target distance',
    customDistance: 'Custom distance (km)',
    customDistancePlaceholder: 'E.g. 15',
    goalTime: 'Goal time (hh:mm or hh:mm:ss)',
    goalTimePlaceholder: '03:45 or 01:48:30',
    planBasedOn: 'Plan based on',
    modeDate: 'Date',
    modeWeeks: 'Weeks',
    raceDate: 'Race date',
    trainingWeeks: 'Training weeks',
    daysPerWeek: 'Training days per week',
    daysSuffix: 'days',
    generatePlan: 'Generate plan',
    reset: 'Reset',
    savedPlans: 'Saved plans',
    savedPlansHint: 'Give your plan a name and save it locally to open again later.',
    savePlanPlaceholder: 'E.g. Rotterdam build-up',
    savePlan: 'Save plan',
    generateBeforeSave: 'Generate a plan before saving.',
    noSavedPlans: 'No saved plans yet.',
    open: 'Open',
    delete: 'Delete',
    planSummary: 'Plan summary',
    summaryRace: 'Target race',
    summaryPeriod: 'Period',
    summaryGoalTime: 'Goal time',
    summaryGoalPace: 'Goal pace',
    summaryWeeks: 'Training weeks',
    summaryDays: 'Days per week',
    downloadPdf: 'Download PDF',
    downloadImage: 'Download image',
    printTable: 'Print table',
    printList: 'Print list',
    showModal: 'Show in modal',
    exportPreviewDay: 'Daily export preview',
    exportPreviewHint: 'This weekly grid is used for image, PDF and print output.',
    trainingPlanLabel: 'Training Plan',
    autoGeneratedPlan: 'Automatically generated running plan',
    week: 'Week',
    date: 'Date',
    total: 'Total',
    detailedPlan: 'Detailed plan with explanation',
    from: 'From',
    distance: 'Distance',
    pace: 'Pace',
    noPlanYet: 'No plan yet',
    noPlanHint: 'Fill in your settings on the left and click',
    preview: 'Preview',
    closeModal: 'Close plan modal',
    restDay: 'Rest day',
    unknownPlanningError: 'Planning error',
    invalidStoredPlanRemoved: 'A saved plan had invalid dates and was removed. Generate a new plan.',
    saveFailed: 'Saving failed.',
    loadFailed: 'Loading failed.',
    generateBeforeExport: 'Generate a plan first.',
    noExportElement: 'No plan element available for export.',
    imageExportFailed: 'Image export failed.',
    pdfExportFailed: 'PDF export failed.',
    generateBeforePrint: 'Generate a plan first to print.',
    fileNameBase: 'training-plan',
    rangeConnector: 'to',
    defaultPlanPrefix: 'Plan',
    savedAtPrefix: 'Saved at',
    raceTypeEasy: 'Easy run',
    raceTypeRecovery: 'Recovery run',
    raceTypeInterval: 'Interval training',
    raceTypeTempo: 'Tempo run',
    raceTypeTempoMarathon: 'Marathon pace',
    raceTypeLong: 'Long run',
    raceTypeRace: 'Race',
  },
  fr: {
    langName: 'Francais',
    appBadge: 'Planificateur Running',
    appTitle: 'Planificateur Marathon & Running',
    appSubtitle: 'Entre ton objectif, la date de course ou le nombre de semaines et recois un plan automatique.',
    settings: 'Parametres',
    language: 'Langue',
    targetDistance: 'Distance cible',
    customDistance: 'Distance perso (km)',
    customDistancePlaceholder: 'Ex. 15',
    goalTime: 'Temps objectif (hh:mm ou hh:mm:ss)',
    goalTimePlaceholder: '03:45 ou 01:48:30',
    planBasedOn: 'Plan base sur',
    modeDate: 'Date',
    modeWeeks: 'Semaines',
    raceDate: 'Date de course',
    trainingWeeks: 'Semaines d entrainement',
    daysPerWeek: 'Jours d entrainement par semaine',
    daysSuffix: 'jours',
    generatePlan: 'Generer le plan',
    reset: 'Reinitialiser',
    savedPlans: 'Plans enregistres',
    savedPlansHint: 'Donne un nom a ton plan et enregistre-le localement pour le rouvrir plus tard.',
    savePlanPlaceholder: 'Ex. Preparation Rotterdam',
    savePlan: 'Enregistrer',
    generateBeforeSave: 'Genere un plan avant de sauvegarder.',
    noSavedPlans: 'Aucun plan enregistre.',
    open: 'Ouvrir',
    delete: 'Supprimer',
    planSummary: 'Resume du plan',
    summaryRace: 'Course cible',
    summaryPeriod: 'Periode',
    summaryGoalTime: 'Temps objectif',
    summaryGoalPace: 'Allure cible',
    summaryWeeks: 'Semaines',
    summaryDays: 'Jours par semaine',
    downloadPdf: 'Telecharger PDF',
    downloadImage: 'Telecharger image',
    printTable: 'Imprimer tableau',
    printList: 'Imprimer liste',
    showModal: 'Afficher en modal',
    exportPreviewDay: 'Apercu export par jour',
    exportPreviewHint: 'Cette grille hebdo est utilisee pour image, PDF et impression.',
    trainingPlanLabel: 'Plan d entrainement',
    autoGeneratedPlan: 'Plan de course genere automatiquement',
    week: 'Semaine',
    date: 'Date',
    total: 'Total',
    detailedPlan: 'Plan detaille avec explication',
    from: 'Du',
    distance: 'Distance',
    pace: 'Allure',
    noPlanYet: 'Pas encore de plan',
    noPlanHint: 'Complete les parametres a gauche puis clique sur',
    preview: 'Apercu',
    closeModal: 'Fermer la fenetre du plan',
    restDay: 'Repos',
    unknownPlanningError: 'Erreur de planification',
    invalidStoredPlanRemoved: 'Un plan enregistre contenait des dates invalides et a ete supprime. Genere un nouveau plan.',
    saveFailed: 'Echec de sauvegarde.',
    loadFailed: 'Echec de chargement.',
    generateBeforeExport: 'Genere d abord un plan.',
    noExportElement: 'Aucun element de plan disponible pour exporter.',
    imageExportFailed: 'Echec export image.',
    pdfExportFailed: 'Echec export PDF.',
    generateBeforePrint: 'Genere d abord un plan pour imprimer.',
    fileNameBase: 'plan-entrainement',
    rangeConnector: 'au',
    defaultPlanPrefix: 'Plan',
    savedAtPrefix: 'Enregistre le',
    raceTypeEasy: 'Sortie facile',
    raceTypeRecovery: 'Recuperation',
    raceTypeInterval: 'Fractionne',
    raceTypeTempo: 'Tempo',
    raceTypeTempoMarathon: 'Allure marathon',
    raceTypeLong: 'Sortie longue',
    raceTypeRace: 'Course',
  },
} as const

type MessageKey = keyof typeof messages.nl

const localeTag = computed(() => {
  if (currentLocale.value === 'en') return 'en-GB'
  if (currentLocale.value === 'fr') return 'fr-FR'
  return 'nl-NL'
})

const languageOptions: { value: AppLocale; label: string }[] = [
  { value: 'nl', label: 'NL' },
  { value: 'en', label: 'EN' },
  { value: 'fr', label: 'FR' },
]

function t(key: MessageKey) {
  return messages[currentLocale.value][key]
}

const raceOptions = computed<{ label: string; value: RaceType }[]>(() => {
  if (currentLocale.value === 'en') {
    return [
      { label: 'Marathon (42.2 km)', value: 'marathon' },
      { label: 'Half marathon (21.1 km)', value: 'half-marathon' },
      { label: '10 km', value: '10k' },
      { label: '5 km', value: '5k' },
      { label: 'Custom distance', value: 'custom' },
    ]
  }

  if (currentLocale.value === 'fr') {
    return [
      { label: 'Marathon (42.2 km)', value: 'marathon' },
      { label: 'Semi-marathon (21.1 km)', value: 'half-marathon' },
      { label: '10 km', value: '10k' },
      { label: '5 km', value: '5k' },
      { label: 'Distance perso', value: 'custom' },
    ]
  }

  return [
    { label: 'Marathon (42.2 km)', value: 'marathon' },
    { label: 'Halve marathon (21.1 km)', value: 'half-marathon' },
    { label: '10 km', value: '10k' },
    { label: '5 km', value: '5k' },
    { label: 'Eigen afstand', value: 'custom' },
  ]
})

const dayOptions = [2, 3, 4, 5, 6, 7]
const weekdayHeaders = computed(() => {
  if (currentLocale.value === 'en') return ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  if (currentLocale.value === 'fr') return ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim']
  return ['Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za', 'Zo']
})

interface ExportCell {
  title: string
  value: string
  dateLabel: string
  type: TrainingSession['type'] | 'rest'
}

interface ExportWeekRow {
  weekNumber: number
  weekEndShort: string
  totalDistanceKm: number
  cells: ExportCell[]
}

type PrintTarget = 'table' | 'list'

const todayISO = computed(() => {
  const now = new Date()
  now.setHours(0, 0, 0, 0)
  return now.toISOString().slice(0, 10)
})

const summaryRows = computed(() => {
  if (!planner.plan) {
    return []
  }

  return [
    { label: t('summaryRace'), value: planner.plan.raceLabel },
    { label: t('summaryPeriod'), value: planDateRange.value },
    { label: t('summaryGoalTime'), value: formatGoalTime(planner.plan.goalTimeMinutes) },
    { label: t('summaryGoalPace'), value: formatPaceValue(planner.plan.targetPaceMinPerKm) },
    { label: t('summaryWeeks'), value: String(planner.plan.totalWeeks) },
    { label: t('summaryDays'), value: String(planner.plan.daysPerWeek) },
  ]
})

const displayError = computed(() => {
  if (localError.value) {
    return localError.value
  }

  if (!planner.lastError) {
    return ''
  }

  if (
    planner.lastError === '__INVALID_STORED_PLAN_ERROR__' ||
    planner.lastError === 'Opgeslagen planning bevatte ongeldige datums en is verwijderd. Genereer een nieuw schema.'
  ) {
    return t('invalidStoredPlanRemoved')
  }

  return planner.lastError
})

const planDateRange = computed(() => {
  if (!planner.plan) {
    return ''
  }
  return `${formatDateLong(planner.plan.startDateISO, currentLocale.value)} ${t('rangeConnector')} ${formatDateLong(planner.plan.endDateISO, currentLocale.value)}`
})

function roundToHalf(value: number) {
  return Math.round(value * 2) / 2
}

function addDays(isoDate: string, days: number) {
  const date = new Date(isoDate)
  date.setDate(date.getDate() + days)
  return date.toISOString().slice(0, 10)
}

function startOfWeekMondayISO(isoDate: string) {
  const date = new Date(isoDate)
  const day = date.getDay()
  const diff = day === 0 ? -6 : 1 - day
  date.setDate(date.getDate() + diff)
  return date.toISOString().slice(0, 10)
}

function formatShortDate(dateISO: string) {
  const date = new Date(dateISO)
  return new Intl.DateTimeFormat(localeTag.value, {
    day: '2-digit',
    month: '2-digit',
  }).format(date)
}

function sessionTypeLabel(type: TrainingSession['type']) {
  if (type === 'easy') return t('raceTypeEasy')
  if (type === 'recovery') return t('raceTypeRecovery')
  if (type === 'interval') return t('raceTypeInterval')
  if (type === 'tempo') return planner.form.raceType === 'marathon' ? t('raceTypeTempoMarathon') : t('raceTypeTempo')
  if (type === 'long') return t('raceTypeLong')
  return t('raceTypeRace')
}

function exportTitle(session: TrainingSession) {
  if (session.type === 'race') {
    return `${t('raceTypeRace')} (${session.weekday})`
  }
  return sessionTypeLabel(session.type)
}

function exportValue(session: TrainingSession) {
  return `${session.distanceKm} km`
}

const exportWeeks = computed<ExportWeekRow[]>(() => {
  if (!planner.plan) {
    return []
  }

  return planner.plan.weeks.map((week) => {
    const sessionsByDate = new Map(week.sessions.map((session) => [session.dateISO, session]))
    const cells: ExportCell[] = []
    let displayedTotalKm = 0
    const raceSession = week.sessions.find((session) => session.type === 'race')

    let gridStartISO = week.startDateISO
    if (raceSession) {
      const weekStartDate = new Date(week.startDateISO)
      const weekEndDate = new Date(addDays(week.startDateISO, 6))
      const raceDate = new Date(raceSession.dateISO)
      const raceInGridRange = raceDate >= weekStartDate && raceDate <= weekEndDate
      if (!raceInGridRange) {
        gridStartISO = startOfWeekMondayISO(raceSession.dateISO)
      }
    }

    for (let dayOffset = 0; dayOffset < 7; dayOffset += 1) {
      const isoDate = addDays(gridStartISO, dayOffset)
      const session = sessionsByDate.get(isoDate)

      if (!session) {
        cells.push({
          title: t('restDay'),
          value: '-',
          dateLabel: formatShortDate(isoDate),
          type: 'rest',
        })
        continue
      }

      cells.push({
        title: exportTitle(session),
        value: exportValue(session),
        dateLabel: formatShortDate(session.dateISO),
        type: session.type,
      })
      displayedTotalKm += session.distanceKm
    }

    return {
      weekNumber: week.weekNumber,
      weekEndShort: formatShortDate(addDays(gridStartISO, 6)),
      totalDistanceKm: roundToHalf(displayedTotalKm),
      cells,
    }
  })
})

function setMode(mode: 'date' | 'weeks') {
  planner.form.mode = mode
}

function generatePlan() {
  localError.value = ''

  try {
    planner.generate(currentLocale.value)
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('unknownPlanningError')
  }
}

function resetPlanner() {
  planner.reset()
  localError.value = ''
}

function defaultPlanName() {
  const now = new Intl.DateTimeFormat(localeTag.value, { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date())
  return planner.plan ? `${planner.plan.raceLabel} ${now}` : `${t('defaultPlanPrefix')} ${now}`
}

function saveNamedPlan() {
  localError.value = ''

  try {
    planner.saveCurrentPlan(savePlanName.value.trim() || defaultPlanName(), currentLocale.value)
    savePlanName.value = ''
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('saveFailed')
  }
}

function loadSavedPlanEntry(planId: string) {
  localError.value = ''

  try {
    planner.loadSavedPlan(planId, currentLocale.value)
    planner.generate(currentLocale.value)
    closePreviewModal()
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('loadFailed')
  }
}

function deleteSavedPlanEntry(planId: string) {
  planner.deleteSavedPlan(planId)
}

function savedPlanPeriod(entry: SavedPlanEntry) {
  return `${formatDateLong(entry.plan.startDateISO, currentLocale.value)} ${t('rangeConnector')} ${formatDateLong(entry.plan.endDateISO, currentLocale.value)}`
}

function savedAtLabel(createdAtISO: string) {
  const date = new Date(createdAtISO)
  if (!Number.isFinite(date.getTime())) {
    return ''
  }

  const label = new Intl.DateTimeFormat(localeTag.value, {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date)

  return `${t('savedAtPrefix')} ${label}`
}

function typeBadgeClass(type: TrainingSession['type']) {
  if (type === 'easy') return 'bg-emerald-100 text-emerald-900'
  if (type === 'recovery') return 'bg-cyan-100 text-cyan-900'
  if (type === 'tempo') return 'bg-amber-100 text-amber-900'
  if (type === 'interval') return 'bg-sky-100 text-sky-900'
  if (type === 'long') return 'bg-violet-100 text-violet-900'
  return 'bg-rose-100 text-rose-900'
}

function exportCellClass(type: ExportCell['type']) {
  if (type === 'easy') return 'bg-emerald-200/75 text-emerald-950'
  if (type === 'recovery') return 'bg-cyan-200/75 text-cyan-950'
  if (type === 'tempo') return 'bg-amber-200/75 text-amber-950'
  if (type === 'interval') return 'bg-sky-200/75 text-sky-950'
  if (type === 'long') return 'bg-violet-200/75 text-violet-950'
  if (type === 'race') return 'bg-rose-300/80 text-rose-950'
  if (type === 'rest') return 'bg-zinc-100 text-zinc-700'
  return ''
}

async function capturePlanCanvas() {
  if (!planner.plan) {
    throw new Error(t('generateBeforeExport'))
  }

  if (!exportElement.value) {
    throw new Error(t('noExportElement'))
  }

  isExporting.value = true
  try {
    return await html2canvas(exportElement.value, {
      scale: 2,
      backgroundColor: '#ffffff',
      useCORS: true,
      scrollX: 0,
      scrollY: -window.scrollY,
    })
  } finally {
    isExporting.value = false
  }
}

async function downloadImage() {
  localError.value = ''

  try {
    const canvas = await capturePlanCanvas()
    const link = document.createElement('a')
    link.download = `${t('fileNameBase')}-${todayISO.value}.png`
    link.href = canvas.toDataURL('image/png')
    link.click()
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('imageExportFailed')
  }
}

async function downloadPdf() {
  localError.value = ''

  try {
    const canvas = await capturePlanCanvas()
    const pdf = new jsPDF('l', 'mm', 'a4')
    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    const margin = 10
    const printableWidth = pageWidth - margin * 2
    const printableHeight = pageHeight - margin * 2

    const imageWidth = printableWidth
    const imageHeight = (canvas.height * imageWidth) / canvas.width
    const imageData = canvas.toDataURL('image/png')

    let remainingHeight = imageHeight
    let yOffset = margin

    pdf.addImage(imageData, 'PNG', margin, yOffset, imageWidth, imageHeight)
    remainingHeight -= printableHeight

    while (remainingHeight > 0) {
      yOffset = margin - (imageHeight - remainingHeight)
      pdf.addPage()
      pdf.addImage(imageData, 'PNG', margin, yOffset, imageWidth, imageHeight)
      remainingHeight -= printableHeight
    }

    pdf.save(`${t('fileNameBase')}-${todayISO.value}.pdf`)
  } catch (error) {
    localError.value = error instanceof Error ? error.message : t('pdfExportFailed')
  }
}

function setPrintTargetClass(target: PrintTarget) {
  document.body.classList.remove('print-target-table', 'print-target-list')
  document.body.classList.add(target === 'table' ? 'print-target-table' : 'print-target-list')
}

function clearPrintTargetClass() {
  document.body.classList.remove('print-target-table', 'print-target-list')
}

async function printPlan(target: PrintTarget) {
  if (!planner.plan) {
    localError.value = t('generateBeforePrint')
    return
  }

  if (isPreviewModalOpen.value) {
    closePreviewModal()
  }

  setPrintTargetClass(target)
  await nextTick()
  window.print()
}

function openPreviewModal() {
  if (!planner.plan) {
    return
  }
  isPreviewModalOpen.value = true
}

function closePreviewModal() {
  isPreviewModalOpen.value = false
}

function handleWindowKeydown(event: KeyboardEvent) {
  if (event.key === 'Escape') {
    closePreviewModal()
  }
}

function handlePopState() {
  const locale = getLocaleFromUrl()
  if (locale !== currentLocale.value) {
    currentLocale.value = locale
  }
}

watch(isPreviewModalOpen, (open) => {
  document.body.classList.toggle('modal-open', open)
})

watch(currentLocale, (locale, previousLocale) => {
  document.documentElement.lang = locale
  syncLocaleInUrl(locale, !previousLocale)

  if (planner.plan) {
    try {
      planner.generate(locale)
      localError.value = ''
    } catch (error) {
      localError.value = error instanceof Error ? error.message : t('unknownPlanningError')
    }
  }
})

onMounted(() => {
  document.documentElement.lang = currentLocale.value
  syncLocaleInUrl(currentLocale.value, true)
  window.addEventListener('keydown', handleWindowKeydown)
  window.addEventListener('afterprint', clearPrintTargetClass)
  window.addEventListener('popstate', handlePopState)
})

onBeforeUnmount(() => {
  document.body.classList.remove('modal-open')
  clearPrintTargetClass()
  window.removeEventListener('keydown', handleWindowKeydown)
  window.removeEventListener('afterprint', clearPrintTargetClass)
  window.removeEventListener('popstate', handlePopState)
})
</script>

<template>
  <main class="min-h-screen bg-background pb-12">
    <div class="mx-auto max-w-[1800px] px-4 py-8 sm:px-6 lg:px-8">
      <header class="hero-shell mb-7 rounded-3xl px-6 py-8 md:px-8 md:py-10">
        <div class="flex flex-wrap items-center justify-between gap-3">
          <p class="inline-flex items-center gap-2 rounded-full bg-muted/80 px-3 py-1 text-xs font-semibold uppercase tracking-[0.14em] text-foreground backdrop-blur">
            <Goal class="h-4 w-4" />
            {{ t('appBadge') }}
          </p>
          <div class="flex items-center gap-2">
            <Label class="mb-0 text-xs uppercase tracking-[0.12em] text-muted-foreground">{{ t('language') }}</Label>
            <select
              v-model="currentLocale"
              class="h-9 rounded-lg border border-border bg-white px-3 text-xs font-semibold uppercase outline-none transition focus:border-zinc-500 focus:ring-2 focus:ring-zinc-300"
            >
              <option v-for="option in languageOptions" :key="option.value" :value="option.value">{{ option.label }}</option>
            </select>
          </div>
        </div>
        <h1 class="mt-3 text-2xl font-bold text-foreground md:text-3xl">{{ t('appTitle') }}</h1>
        <p class="mt-4 max-w-3xl text-sm font-semibold leading-relaxed text-muted-foreground md:text-base">
          {{ t('appSubtitle') }}
        </p>
      </header>

      <div class="grid items-start gap-6 lg:grid-cols-[380px,minmax(0,1fr)] print:block">
        <Card class="h-fit p-5 print:hidden lg:sticky lg:top-6">
          <h2 class="mb-4 text-xl font-semibold">{{ t('settings') }}</h2>

          <div class="space-y-4">
            <div>
              <Label>{{ t('targetDistance') }}</Label>
              <select
                v-model="planner.form.raceType"
                class="h-10 w-full rounded-xl border border-border bg-white px-3 text-sm font-medium outline-none transition focus:border-zinc-500 focus:ring-2 focus:ring-zinc-300"
              >
                <option v-for="option in raceOptions" :key="option.value" :value="option.value">
                  {{ option.label }}
                </option>
              </select>
            </div>

            <div v-if="planner.form.raceType === 'custom'">
              <Label>{{ t('customDistance') }}</Label>
              <Input
                :model-value="planner.form.customDistanceKm"
                type="number"
                min="1"
                max="100"
                step="0.5"
                :placeholder="t('customDistancePlaceholder')"
                @update:model-value="planner.form.customDistanceKm = Number($event)"
              />
            </div>

            <div>
              <Label>{{ t('goalTime') }}</Label>
              <Input v-model="planner.form.goalTime" :placeholder="t('goalTimePlaceholder')" />
            </div>

            <div>
              <Label>{{ t('planBasedOn') }}</Label>
              <div class="grid grid-cols-2 gap-2">
                <Button
                  type="button"
                  :variant="planner.form.mode === 'date' ? 'default' : 'outline'"
                  class="w-full"
                  @click="setMode('date')"
                >
                  <Calendar class="h-4 w-4" />
                  {{ t('modeDate') }}
                </Button>
                <Button
                  type="button"
                  :variant="planner.form.mode === 'weeks' ? 'default' : 'outline'"
                  class="w-full"
                  @click="setMode('weeks')"
                >
                  <RefreshCcw class="h-4 w-4" />
                  {{ t('modeWeeks') }}
                </Button>
              </div>
            </div>

            <div v-if="planner.form.mode === 'date'">
              <Label>{{ t('raceDate') }}</Label>
              <Input v-model="planner.form.raceDate" type="date" :min="todayISO" />
            </div>

            <div v-else>
              <Label>{{ t('trainingWeeks') }}</Label>
              <Input
                :model-value="planner.form.trainingWeeks"
                type="number"
                min="2"
                max="52"
                step="1"
                @update:model-value="planner.form.trainingWeeks = Number($event)"
              />
            </div>

            <div>
              <Label>{{ t('daysPerWeek') }}</Label>
              <select
                v-model.number="planner.form.daysPerWeek"
                class="h-10 w-full rounded-xl border border-border bg-white px-3 text-sm font-medium outline-none transition focus:border-zinc-500 focus:ring-2 focus:ring-zinc-300"
              >
                <option v-for="days in dayOptions" :key="days" :value="days">{{ days }} {{ t('daysSuffix') }}</option>
              </select>
            </div>

            <div class="grid grid-cols-1 gap-2 pt-1">
              <Button type="button" size="lg" @click="generatePlan">{{ t('generatePlan') }}</Button>
              <Button type="button" variant="secondary" @click="resetPlanner">{{ t('reset') }}</Button>
            </div>

            <p v-if="displayError" class="rounded-lg bg-zinc-200 px-3 py-2 text-sm text-zinc-900">
              {{ displayError }}
            </p>
          </div>
        </Card>

        <section>
          <Card class="mb-4 p-5 print:hidden">
            <h2 class="mb-2 text-2xl font-bold">{{ t('savedPlans') }}</h2>
            <p class="text-sm font-medium text-muted-foreground">
              {{ t('savedPlansHint') }}
            </p>

            <div class="mt-4 grid gap-2 sm:grid-cols-[1fr,auto]">
              <Input
                v-model="savePlanName"
                :disabled="!planner.plan"
                :placeholder="t('savePlanPlaceholder')"
                @keydown.enter.prevent="saveNamedPlan"
              />
              <Button type="button" :disabled="!planner.plan" @click="saveNamedPlan">
                <Save class="h-4 w-4" />
                {{ t('savePlan') }}
              </Button>
            </div>

            <p v-if="!planner.plan" class="mt-2 text-xs font-medium text-muted-foreground">
              {{ t('generateBeforeSave') }}
            </p>

            <div class="mt-4 space-y-2">
              <p v-if="!planner.savedPlans.length" class="rounded-lg border border-dashed border-border bg-secondary/40 px-3 py-2 text-sm text-muted-foreground">
                {{ t('noSavedPlans') }}
              </p>

              <article
                v-for="saved in planner.savedPlans"
                :key="saved.id"
                class="flex flex-col gap-3 rounded-xl border border-border/80 bg-white/80 px-3 py-3 sm:flex-row sm:items-start sm:justify-between"
              >
                <div class="min-w-0">
                  <h3 class="truncate text-sm font-semibold text-foreground">{{ saved.name }}</h3>
                  <p class="text-xs text-muted-foreground">{{ saved.plan.raceLabel }} · {{ savedPlanPeriod(saved) }}</p>
                  <p class="text-xs text-muted-foreground/90">{{ savedAtLabel(saved.createdAtISO) }}</p>
                </div>
                <div class="flex shrink-0 gap-2">
                  <Button type="button" size="sm" variant="outline" @click="loadSavedPlanEntry(saved.id)">
                    <FolderOpen class="h-3.5 w-3.5" />
                    {{ t('open') }}
                  </Button>
                  <Button
                    type="button"
                    size="sm"
                    variant="ghost"
                    class="text-zinc-700 hover:bg-zinc-200 hover:text-zinc-900"
                    @click="deleteSavedPlanEntry(saved.id)"
                  >
                    <Trash2 class="h-3.5 w-3.5" />
                    {{ t('delete') }}
                  </Button>
                </div>
              </article>
            </div>
          </Card>

          <Card v-if="planner.plan" class="mb-4 p-5 print:hidden">
            <h2 class="mb-3 text-2xl font-bold">{{ t('planSummary') }}</h2>
            <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
              <div v-for="row in summaryRows" :key="row.label" class="rounded-xl border border-border/70 bg-secondary/60 px-3 py-2">
                <p class="text-xs uppercase tracking-[0.11em] text-muted-foreground">{{ row.label }}</p>
                <p class="text-sm font-semibold text-foreground">{{ row.value }}</p>
              </div>
            </div>

            <div class="mt-4 flex flex-wrap gap-2">
              <Button type="button" variant="outline" :disabled="isExporting" @click="downloadPdf">
                <FileText class="h-4 w-4" />
                {{ t('downloadPdf') }}
              </Button>
              <Button type="button" variant="outline" :disabled="isExporting" @click="downloadImage">
                <FileImage class="h-4 w-4" />
                {{ t('downloadImage') }}
              </Button>
              <Button type="button" variant="secondary" @click="printPlan('table')">
                <Printer class="h-4 w-4" />
                {{ t('printTable') }}
              </Button>
              <Button type="button" variant="outline" @click="printPlan('list')">
                <Printer class="h-4 w-4" />
                {{ t('printList') }}
              </Button>
              <Button type="button" variant="outline" @click="openPreviewModal">
                <Expand class="h-4 w-4" />
                {{ t('showModal') }}
              </Button>
            </div>
          </Card>

          <Card v-if="planner.plan" id="printable-plan-section" class="mb-4 hidden p-4 md:block print:block">
            <div class="mb-3 print:hidden">
              <h2 class="text-2xl font-bold">{{ t('exportPreviewDay') }}</h2>
              <p class="text-sm font-medium text-muted-foreground">
                {{ t('exportPreviewHint') }}
              </p>
            </div>

            <div class="overflow-hidden rounded-xl border border-border/90 bg-white/80">
              <div id="printable-plan" ref="exportElement" class="export-sheet">
                <header class="export-sheet-header">
                  <h3>{{ planner.plan.raceLabel }} {{ t('trainingPlanLabel') }} · {{ planDateRange }}</h3>
                  <p>{{ t('autoGeneratedPlan') }}</p>
                </header>

                <table class="export-table">
                  <thead>
                    <tr>
                      <th class="week-col">{{ t('week') }}</th>
                      <th v-for="day in weekdayHeaders" :key="day">{{ day }}</th>
                      <th class="date-col">{{ t('date') }}</th>
                      <th class="km-col">{{ t('total') }}</th>
                    </tr>
                  </thead>
                  <tbody>
                    <template v-for="week in exportWeeks" :key="week.weekNumber">
                      <tr class="separator-row">
                        <td colspan="10" />
                      </tr>
                      <tr class="week-row">
                        <td class="week-number">{{ week.weekNumber }}.</td>
                        <td
                          v-for="(cell, cellIndex) in week.cells"
                          :key="`${week.weekNumber}-${cellIndex}`"
                          class="day-cell"
                        >
                          <div class="cell-title">{{ cell.title }}</div>
                          <div class="cell-date">{{ cell.dateLabel }}</div>
                          <div :class="['cell-value', exportCellClass(cell.type)]">{{ cell.value }}</div>
                        </td>
                        <td class="week-end-date">{{ week.weekEndShort }}</td>
                        <td class="week-km">{{ week.totalDistanceKm }} km</td>
                      </tr>
                    </template>
                    <tr class="separator-row">
                      <td colspan="10" />
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </Card>

          <Card v-if="planner.plan" id="printable-list-section" class="p-5">
            <div class="mb-5 border-b border-border pb-4">
              <h2 class="text-3xl font-bold">{{ t('detailedPlan') }}</h2>
              <p class="mt-2 text-sm font-medium text-muted-foreground">
                {{ t('from') }} {{ planDateRange }}
              </p>
            </div>

            <div class="space-y-4">
              <article
                v-for="week in planner.plan.weeks"
                :key="week.weekNumber"
                class="animate-rise rounded-xl border border-border bg-white p-4"
                :style="{ animationDelay: `${week.weekNumber * 40}ms` }"
              >
                <div class="mb-3 flex flex-wrap items-center justify-between gap-3">
                  <div>
                    <h3 class="text-lg font-semibold">{{ t('week') }} {{ week.weekNumber }}</h3>
                    <p class="text-sm text-muted-foreground">
                      {{ formatDateLong(week.startDateISO, currentLocale) }} - {{ formatDateLong(week.endDateISO, currentLocale) }}
                    </p>
                  </div>
                  <span class="rounded-full bg-secondary px-3 py-1 text-xs font-semibold">{{ week.totalDistanceKm }} km</span>
                </div>

                <p class="mb-3 rounded-lg bg-muted px-3 py-2 text-sm text-muted-foreground">{{ week.focus }}</p>

                <div class="space-y-2">
                  <div
                    v-for="session in week.sessions"
                    :key="session.id"
                    class="rounded-lg border border-border/70 bg-card p-3"
                  >
                    <div class="mb-1 flex flex-wrap items-center justify-between gap-2">
                      <p class="font-semibold text-foreground">
                        {{ session.weekday }} {{ formatDateLong(session.dateISO, currentLocale) }} - {{ session.title }}
                      </p>
                      <span :class="['rounded-full px-2.5 py-1 text-xs font-semibold capitalize', typeBadgeClass(session.type)]">
                        {{ sessionTypeLabel(session.type) }}
                      </span>
                    </div>
                    <p class="mb-1 text-sm text-foreground">
                      <strong>{{ t('distance') }}:</strong> {{ session.distanceKm }} km · <strong>{{ t('pace') }}:</strong> {{ session.pace }}
                    </p>
                    <p class="text-sm text-muted-foreground">{{ session.description }}</p>
                  </div>
                </div>
              </article>
            </div>
          </Card>

          <Card v-else class="grid min-h-80 place-items-center p-8 text-center">
            <div>
              <Download class="mx-auto mb-3 h-8 w-8 text-muted-foreground" />
              <h2 class="text-2xl font-bold">{{ t('noPlanYet') }}</h2>
              <p class="mt-2 text-sm text-muted-foreground">
                {{ t('noPlanHint') }} <strong>{{ t('generatePlan') }}</strong>.
              </p>
            </div>
          </Card>
        </section>
      </div>
    </div>

    <Teleport to="body">
      <div v-if="isPreviewModalOpen" class="modal-overlay">
        <button class="modal-backdrop" :aria-label="t('closeModal')" @click="closePreviewModal" />
        <section class="modal-panel">
          <header class="modal-panel-header">
            <div>
              <p class="text-[11px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">{{ t('preview') }}</p>
              <h3 class="text-base font-bold text-foreground md:text-lg">
                {{ planner.plan?.raceLabel }} {{ t('trainingPlanLabel') }}
              </h3>
              <p class="text-sm font-medium text-muted-foreground">{{ planDateRange }}</p>
            </div>
            <Button type="button" variant="ghost" class="h-9 w-9 rounded-full p-0" @click="closePreviewModal">
              <X class="h-4 w-4" />
            </Button>
          </header>

          <div class="modal-panel-body">
            <div class="overflow-hidden rounded-xl border border-border/90 bg-white/80">
              <div class="export-sheet">
                <header class="export-sheet-header">
                  <h3>{{ planner.plan?.raceLabel }} {{ t('trainingPlanLabel') }} · {{ planDateRange }}</h3>
                  <p>{{ t('autoGeneratedPlan') }}</p>
                </header>

                <table class="export-table">
                  <thead>
                    <tr>
                      <th class="week-col">{{ t('week') }}</th>
                      <th v-for="day in weekdayHeaders" :key="`modal-${day}`">{{ day }}</th>
                      <th class="date-col">{{ t('date') }}</th>
                      <th class="km-col">{{ t('total') }}</th>
                    </tr>
                  </thead>
                  <tbody>
                    <template v-for="week in exportWeeks" :key="`modal-${week.weekNumber}`">
                      <tr class="separator-row">
                        <td colspan="10" />
                      </tr>
                      <tr class="week-row">
                        <td class="week-number">{{ week.weekNumber }}.</td>
                        <td
                          v-for="(cell, cellIndex) in week.cells"
                          :key="`modal-${week.weekNumber}-${cellIndex}`"
                          class="day-cell"
                        >
                          <div class="cell-title">{{ cell.title }}</div>
                          <div class="cell-date">{{ cell.dateLabel }}</div>
                          <div :class="['cell-value', exportCellClass(cell.type)]">{{ cell.value }}</div>
                        </td>
                        <td class="week-end-date">{{ week.weekEndShort }}</td>
                        <td class="week-km">{{ week.totalDistanceKm }} km</td>
                      </tr>
                    </template>
                    <tr class="separator-row">
                      <td colspan="10" />
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </section>
      </div>
    </Teleport>
  </main>
</template>
